// CHECKPOINT 6 — branding cadence, per reel.
//
// Section 7, tightened for reel length: no gap beyond ~20-25 s between Shivansh
// appearances (vs 30-40 s in the long format), MOTU a small number of times
// INCLUDING mid-reel, and www.shivanshelectronics.in the most-repeated single
// contact detail.
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { loadSchedule, PROJ } from "./_load.mjs";

const REEL = Number(process.argv[2] ?? 1);
const { BEATS, BEAT_STARTS, frames } = await loadSchedule(REEL);
const MAX_GAP = 25;

const tc = (f) => {
  const s = f / 30;
  return `${String(Math.floor(s / 60)).padStart(2, "0")}:${String(Math.floor(s % 60)).padStart(2, "0")}`;
};

function shivansh(b) {
  if (b.brand === "beat") return "full branding beat (logo + role + URL + contact)";
  if (b.brand === "cornerLogo") return "corner logo + URL";
  if (b.brand === "lowerThird") return "lower-third logo + URL";
  if (b.kind === "cta") return "CTA panel (logo + URL + socials)";
  if (b.kind === "outro") return "outro lockup (logo + URL)";
  if (b.kind === "price") return "distributor line + dual price";
  return null;
}
const motu = (b) => (b.motu ? "MOTU logo" : b.kind === "outro" ? "MOTU logo" : null);

const rows = BEATS.map((b, i) => ({
  b, start: BEAT_STARTS[i], end: BEAT_STARTS[i] + frames(b.sec),
  s: shivansh(b), m: motu(b),
}));
const sRows = rows.filter((r) => r.s);
const mRows = rows.filter((r) => r.m);

console.log(`REEL ${REEL} — SHIVANSH ELECTRONICS`);
let prevEnd = 0, worst = 0, worstAt = "";
for (const r of sRows) {
  const gap = (r.start - prevEnd) / 30;
  if (gap > worst) { worst = gap; worstAt = tc(prevEnd); }
  console.log(`  ${tc(r.start)}–${tc(r.end)}  ${r.b.id.padEnd(16)} ${r.s}` + (gap > 0.5 ? `   (gap ${gap.toFixed(0)}s)` : ""));
  prevEnd = Math.max(prevEnd, r.end);
}
const last = BEAT_STARTS[BEATS.length - 1] + frames(BEATS[BEATS.length - 1].sec);
const tailGap = (last - prevEnd) / 30;
console.log(`\n  appearances: ${sRows.length}   longest gap: ${worst.toFixed(0)}s (from ${worstAt})   trailing: ${tailGap.toFixed(0)}s`);

console.log("\nMOTU");
for (const r of mRows) console.log(`  ${tc(r.start)}–${tc(r.end)}  ${r.b.id.padEnd(16)} ${r.m}`);
console.log(`  appearances: ${mRows.length}`);

const urlForms = ["full branding beat (logo + role + URL + contact)", "corner logo + URL",
                  "lower-third logo + URL", "CTA panel (logo + URL + socials)", "outro lockup (logo + URL)"];
const urlCount = sRows.filter((r) => urlForms.includes(r.s)).length;
const socialCount = sRows.filter((r) => r.s.includes("socials")).length + BEATS.filter((b) => b.brand === "beat").length;
console.log(`\nwww.shivanshelectronics.in on screen: ${urlCount}   next-most-repeated detail: ${socialCount}`);

const midReel = mRows.some((r) => r.start > 5340 * 0.2 && r.start < 5340 * 0.8);
const gapOk = worst <= MAX_GAP && tailGap <= MAX_GAP;
const motuOk = mRows.length >= 3 && midReel;
const urlOk = urlCount > socialCount;
console.log("\nchecks");
console.log(`  ${gapOk ? "ok  " : "FAIL"} no Shivansh gap over ${MAX_GAP}s`);
console.log(`  ${motuOk ? "ok  " : "FAIL"} MOTU a small number of times incl. mid-reel`);
console.log(`  ${urlOk ? "ok  " : "FAIL"} website is the most-repeated single detail`);

writeFileSync(resolve(PROJ, `BRANDING_CADENCE_REEL${REEL}.md`), `# Branding cadence — Reel ${REEL}

Generated by \`npm run branding\` from the same schedule that renders the reel.

Every logo appearance draws the supplied file exactly as given — opaque, with
its own white background, never alpha-keyed — **directly on the video with no
box, card or plate**, and always clear of the caption-safe zone (top 180px,
bottom 220px).

## Shivansh Electronics — ${sRows.length} appearances (longest gap ${worst.toFixed(0)}s, guideline ≤${MAX_GAP}s)

| In | Out | Beat | Form |
|---|---|---|---|
${sRows.map((r) => `| ${tc(r.start)} | ${tc(r.end)} | \`${r.b.id}\` | ${r.s} |`).join("\n")}

## MOTU — ${mRows.length} appearances

| In | Out | Beat |
|---|---|---|
${mRows.map((r) => `| ${tc(r.start)} | ${tc(r.end)} | \`${r.b.id}\` |`).join("\n")}

- \`www.shivanshelectronics.in\` on screen: **${urlCount}** — more than any other single contact detail
`);
console.log(`\nwrote BRANDING_CADENCE_REEL${REEL}.md`);
const pass = gapOk && motuOk && urlOk;
console.log(pass ? "BRANDING: PASS" : "BRANDING: FAIL");
process.exit(pass ? 0 : 1);
