// Copies the repo-root product images into public/img/ under stable slugs,
// and emits src/assets.ts. public/img/ is gitignored so the binaries are never
// duplicated in version control - re-run this after cloning.
//
//   node sync-assets.mjs
//
import { readFileSync, writeFileSync, mkdirSync, copyFileSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..');
const outDir = join(here, 'public', 'img');
mkdirSync(outDir, { recursive: true });

const assets = JSON.parse(readFileSync(join(here, 'assets.json'), 'utf8'));

let copied = 0;
const missing = [];
for (const a of assets) {
  const src = join(repo, a.src);
  if (!existsSync(src)) { missing.push(a.src); continue; }
  copyFileSync(src, join(outDir, a.slug));
  copied++;
}

// Brand logos - used only in the Part 3 CTA block (see prompt section 4a/7).
const logos = [
  ['SHIVANSH ELECTRONICS LOGO FOR VIDEO.png', 'logo-shivansh.png'],
  ['MOTU LOGO.png', 'logo-motu.png'],
];
for (const [src, dst] of logos) {
  const p = join(repo, src);
  if (existsSync(p)) { copyFileSync(p, join(outDir, dst)); copied++; }
  else missing.push(src);
}

const ts = `// AUTO-GENERATED by sync-assets.mjs - do not edit by hand.
// Content classifications are derived from visual inspection of every image,
// NOT from filenames (filenames do not reliably identify the product depicted).
export type AssetClass = 'hero' | 'macro' | 'panel' | 'software' | 'diagram' | 'logo' | 'context';

export type Asset = {
  idx: number;
  /** original repo filename */
  src: string;
  /** slug under public/img/ */
  slug: string;
  desc: string;
  cls: AssetClass;
  /** product actually depicted, or 'shared' */
  prod: '10pre' | '16A' | '848' | 'shared';
  part: 1 | 2 | 3;
  /** modal border colour, so a contained image dissolves into its plate */
  edge: string;
  /** border luminance 0..1; <0.45 means the source is a dark-field image */
  lum: number;
  /** native pixel dimensions */
  w: number;
  h: number;
};

export const ASSETS: Asset[] = ${JSON.stringify(assets, null, 1)};

export const byIdx = (i: number): Asset => {
  const a = ASSETS.find((x) => x.idx === i);
  if (!a) throw new Error(\`no asset #\${i}\`);
  return a;
};

export const img = (i: number): string => \`img/\${byIdx(i).slug}\`;

export const partAssets = (p: 1 | 2 | 3): Asset[] => ASSETS.filter((a) => a.part === p);
`;
writeFileSync(join(here, 'src', 'assets.ts'), ts);

console.log(`copied ${copied} files -> public/img/`);
if (missing.length) { console.error('MISSING:', missing); process.exit(1); }
console.log(`wrote src/assets.ts (${assets.length} catalogued)`);
