// CURATED asset registry — generated by scripts/build-manifest.mjs + copy-assets.mjs.
//
// 26 images, every one of them already in the 298 s master reel's curated 61.
// Section 0a asks this reel to find the strongest SUBSET of that set rather
// than re-curate from the 120-image inventory; scripts/build-manifest.mjs
// enforces that by throwing if an index appears here that the master reel did
// not select.
//
// Keyed by the stable index from the repository-wide visual inventory, NOT by
// filename. The supplied filename product prefixes are demonstrably unreliable:
// "MOTU 10pre (23).jpg", "MOTU 16A (3).jpg" and "MOTU 848 (6).jpg" decode to
// identical pixels. Identity is a pixel hash; classification came from looking.
import { staticFile } from "remotion";
import manifest from "../asset-manifest.json";

export type Bucket = "10pre" | "16A" | "848" | "AVBSwitch" | "Network" | "Shared" | "Brand";

export type AssetEntry = {
  idx: number;
  file: string;
  aliases: string[];
  hash: string;
  w: number;
  h: number;
  fmt: string;
  ar: number;
  product: Bucket;
  tier: "hero" | "support";
  slug: string;
  ext: string;
  /** Auto-detected from the image's own four corners at asset-copy time. */
  bg: "light" | "mixed" | "dark";
  border: number;
  /** Whether the staged file carries an alpha channel — see Plate. */
  alpha: boolean;
};

export const ASSETS = manifest as AssetEntry[];
const BY_IDX = new Map<number, AssetEntry>(ASSETS.map((a) => [a.idx, a]));

export function meta(idx: number): AssetEntry {
  const a = BY_IDX.get(idx);
  if (!a) throw new Error(`No curated asset with index ${idx}`);
  return a;
}
export function img(idx: number): string {
  const a = meta(idx);
  return staticFile(`images/${a.slug}.${a.ext}`);
}
export const ar = (idx: number): number => meta(idx).ar;

export const LOGO = { motu: 121, shivansh: 122 } as const;

// ─────────────────── The hook, fused with the thesis (Section 4, beat 1)
/** Three front panels that could not look more different, under one claim. */
export const FACES = { tenpre: 9, s16a: 62, s848: 18 } as const;
/** The same three units whole, as peers — setup and payoff of one argument. */
export const ELEV = { tenpre: 30, s16a: 76, s848: 85 } as const;

// ─────────────────────────── The ecosystem flow (Section 4, beat 2)
export const SHARED = {
  ess: 24, thunderbolt: 26,
  cuemixPatchbay: 54, cuemixMonitor: 11,
  /** All three interfaces listed in one software window. */
  discovery: 31,
} as const;

export const HERO = {
  /** MACRO-TO-FULL-REVEAL #1 — the panel that does not explain itself. */
  s16a: 79,
  s16aRear: 51,   // Port Density Sweep across the 32-jack wall
  tenpre: 39,
  tenpreRear: 35,
  s848: 110,
  s848Monitor: 97,
} as const;

// ───────────────────────────────── Network & scale (Section 4, beat 3)
export const NET = {
  builtInPort: 20,      // Data Flow Reveal — the port already in every chassis
  topology: 68,
  /** MACRO-TO-FULL-REVEAL #2 — the payoff of the "one network" claim. */
  switchPorts: 112,
  ieeeAvb: 115, milan: 100,
} as const;

// ───────────────────────── Synthesis & CTA (Section 4, beat 4)
/** One hero angle per product — the closing ecosystem climax. */
export const CLIMAX = { tenpre: 41, s16a: 80, s848: 111, avbsw: 114 } as const;

// ───────────────────────────────────────────────────────────────── audio
export const MUSIC = (slug: string): string => staticFile(`audio/music/${slug}.mp3`);
export const SFX = (name: string): string => staticFile(`audio/sfx/${name}.wav`);
export const VO = (): string => staticFile(`vo/voiceover-compressed-reel.mp3`);

export type SfxKey =
  | "encoder-detent" | "encoder-detent-hi" | "encoder-detent-lo" | "encoder-detent-top"
  | "encoder-detent-mid" | "encoder-turn"
  | "rj45-snap" | "rj45-snap-soft" | "talkback-engage"
  | "relay-tick" | "relay-tick-hi" | "relay-tick-lo"
  | "relay-tick-top" | "counter-tick" | "counter-tick-hi" | "counter-tick-lo"
  | "rack-seat"
  | "avb-ping-hi" | "avb-ping-mid" | "avb-ping-lo" | "avb-ping-top" | "avb-ping-alt"
  | "avb-ping-warm"
  | "gptp-sync" | "gptp-lock" | "gptp-drift"
  | "data-stream" | "data-stream-short" | "data-stream-long" | "link-establish"
  | "panel-air" | "panel-air-soft" | "panel-air-hi" | "panel-air-tight";
