// ─────────────────────────────────────────────────────────────────────────────
// THE SPEECH SCRIPT — single source of truth for this deliverable.
//
// This one file produces BOTH:
//   1. VO_SCRIPT_EXPLAINER_REEL.md — the timestamped read-aloud script the
//      client records (Section 8), generated by scripts/build-script.mjs
//   2. every on-screen caption in the reel, with its own timing
//
// They cannot drift apart, because they are the same data.
//
// TIMING MODEL (Section 8: "narration pacing governs this reel"). Each caption
// is a short spoken phrase. Its duration is derived from its SPOKEN syllable-
// weighted word count at WPM, never guessed. Numerals are expanded to how they
// are actually said ("125 dB" -> "one hundred twenty five d B" = 6 words), so
// a spec-dense line is budgeted the time it really takes to read aloud.
//
// The reel's scene structure is then anchored to those derived timestamps.
// ─────────────────────────────────────────────────────────────────────────────

/** Words per minute the script is written to. Section 8 requires 150–165. */
export const WPM = 165;

/** Gap held after each segment so the reader can breathe and the edit can cut. */
export const SEGMENT_GAP = 0.55;

/** Extra beat after a caption that ends a thought. */
export const BEAT = 0.26;

export type Caption = {
  /** The phrase, exactly as spoken and exactly as captioned on screen. */
  t: string;
  /** Substring(s) rendered in the product accent colour + bold. */
  e?: string;
  /** How many words this really is when read aloud (numerals expand). */
  sw?: number;
  /** Hold an extra beat after this caption — end of a sentence or a reveal. */
  beat?: boolean;
};

export type SegmentId = "open" | "s16a" | "s848" | "s10pre" | "sswitch" | "close";

export type Segment = {
  id: SegmentId;
  /** Product key into THEME.product, or null for ecosystem-level segments. */
  product: "p16a" | "p848" | "p10pre" | "pswitch" | null;
  /** Chapter label burnt into the frame for the whole segment. */
  label: string;
  /** Which background environment this segment lives in (Section 2, item 3). */
  env: "light" | "dark";
  captions: Caption[];
};

export const SEGMENTS: Segment[] = [
  // ── COLD OPEN ──────────────────────────────────────────────────────────────
  // Establishes the ecosystem BEFORE naming a product (Section 4), and sets up
  // the "same DNA, different front end" frame that governs everything after.
  {
    id: "open",
    product: null,
    label: "MOTU AVB",
    env: "dark",
    captions: [
      { t: "Four MOTU products.", e: "Four" },
      { t: "One network.", e: "One network", beat: true },
      { t: "The 16A, the 848," },
      { t: "and the 10pre", e: "10pre" },
      { t: "are the same platform.", e: "same platform", beat: true },
      { t: "The same Thunderbolt 4 connection.", e: "Thunderbolt 4", sw: 6 },
      { t: "The same 64-channel mixer.", e: "64-channel", sw: 6 },
      { t: "The same AVB engine.", e: "AVB engine", sw: 5 },
      { t: "The same software.", e: "software", beat: true },
      { t: "What changes", e: "changes" },
      { t: "is the front panel.", e: "front panel", beat: true },
    ],
  },

  // ── MOTU 16A ───────────────────────────────────────────────────────────────
  // Zero preamps, maximum clean line I/O, DC-coupled CV, for facilities that
  // already own their front end.
  {
    id: "s16a",
    product: "p16a",
    label: "MOTU 16A",
    env: "light",
    captions: [
      { t: "Start with the 16A.", e: "16A", sw: 6 },
      { t: "It has no microphone preamps.", e: "no" },
      { t: "That is the point.", beat: true },
      { t: "Sixteen balanced line inputs.", e: "Sixteen" },
      { t: "Sixteen DC-coupled outputs.", e: "DC-coupled", sw: 6 },
      { t: "Thirty-two in, thirty-four out.", e: "Thirty-two", sw: 6, beat: true },
      { t: "Built for a room that already owns", e: "already owns" },
      { t: "its front end.", e: "front end", beat: true },
      { t: "A rack of outboard preamps." },
      { t: "A console. A patchbay.", e: "patchbay", beat: true },
      { t: "You wire it in once.", e: "once", beat: true },
      { t: "Every output is DC-coupled,", e: "Every output", sw: 6 },
      { t: "so it sends control voltage", e: "control voltage" },
      { t: "straight into a Eurorack system.", e: "Eurorack", beat: true },
      { t: "125 dB of dynamic range.", e: "125 dB", sw: 8 },
      { t: "ESS Sabre32 conversion.", e: "Sabre32", sw: 5, beat: true },
    ],
  },

  // ── MOTU 848 ───────────────────────────────────────────────────────────────
  // 4 preamps + 8 line inputs, A/B/C monitoring, dual independent headphone
  // cues — the balanced mid-tier control-room product.
  {
    id: "s848",
    product: "p848",
    label: "MOTU 848",
    env: "dark",
    captions: [
      { t: "The 848 adds a front end.", e: "848", sw: 7 },
      { t: "Only as much as most rooms need.", beat: true },
      { t: "Four combo preamps on the front panel.", e: "Four" },
      { t: "74 dB of gain.", e: "74 dB", sw: 6 },
      { t: "Minus 129 dBu of input noise.", e: "129", sw: 8, beat: true },
      { t: "Behind them, eight more line inputs", e: "eight" },
      { t: "and twelve outputs.", e: "twelve", beat: true },
      { t: "Inserts on channels three and four,", e: "Inserts" },
      { t: "for the compressor you want.", beat: true },
      { t: "What makes it a control room", e: "control room" },
      { t: "is the monitoring.", e: "monitoring", beat: true },
      { t: "A, B, C speaker switching.", e: "A, B, C", sw: 6 },
      { t: "Two headphone outputs,", e: "Two" },
      { t: "each with its own cue mix.", e: "own cue mix", beat: true },
      { t: "The presenter hears one thing." },
      { t: "The remote guest hears another.", e: "remote guest" },
      { t: "Same box.", e: "Same box", beat: true },
    ],
  },

  // ── MOTU 10pre ─────────────────────────────────────────────────────────────
  // Highest preamp count in the family; the front/rear ergonomic split is the
  // story, not the number on its own.
  {
    id: "s10pre",
    product: "p10pre",
    label: "MOTU 10pre",
    env: "light",
    captions: [
      { t: "The 10pre takes that as far as", e: "10pre", sw: 8 },
      { t: "the range goes.", beat: true },
      { t: "Ten combo preamps.", e: "Ten" },
      { t: "48 volt phantom and a 20 dB pad", e: "48 volt", sw: 11 },
      { t: "on every channel.", e: "every channel", beat: true },
      { t: "The split is the real design.", e: "split", beat: true },
      { t: "Six sit on the rear panel.", e: "Six" },
      { t: "Wire those into the patchbay once", e: "once" },
      { t: "and leave them.", beat: true },
      { t: "Four are on the front,", e: "Four" },
      { t: "where you need a microphone in your hand" },
      { t: "and a channel in ten seconds.", e: "ten seconds", beat: true },
      { t: "Same converters as the 848.", e: "Same", sw: 6 },
      { t: "Same mixer. Same network.", e: "Same network" },
      { t: "Just more microphones at once.", e: "more microphones", beat: true },
    ],
  },

  // ── MOTU AVB SWITCH ────────────────────────────────────────────────────────
  // Reframed entirely at network / system level (Section 10: never preamp or
  // channel-count language — it has neither).
  {
    id: "sswitch",
    product: "pswitch",
    label: "MOTU AVB Switch",
    env: "dark",
    captions: [
      { t: "The AVB Switch has no preamps.", e: "no preamps", sw: 7 },
      { t: "No analogue inputs. No outputs.", e: "No", beat: true },
      { t: "Not that kind of product.", beat: true },
      { t: "It is six Gigabit ports", e: "six" },
      { t: "that turn separate interfaces", e: "separate" },
      { t: "into one system.", e: "one system", beat: true },
      { t: "802.1AS locks every device", e: "802.1AS", sw: 9 },
      { t: "to one clock,", e: "one clock" },
      { t: "accurate to the nanosecond.", e: "nanosecond", beat: true },
      { t: "Credit-based shaping reserves the bandwidth", e: "reserves", sw: 7 },
      { t: "in hardware,", e: "hardware" },
      { t: "so Wi-Fi on the same cable", sw: 7 },
      { t: "cannot interrupt the audio.", e: "cannot interrupt", beat: true },
      { t: "512 streams.", e: "512", sw: 4 },
      { t: "Up to 4,096 channels.", e: "4,096", sw: 9, beat: true },
      { t: "And on a stage,", e: "stage" },
      { t: "one CAT-6 run replaces the snake.", e: "replaces the snake", sw: 8, beat: true },
    ],
  },

  // ── ECOSYSTEM SYNTHESIS / CLOSE ────────────────────────────────────────────
  {
    id: "close",
    product: null,
    label: "One Ecosystem",
    env: "light",
    captions: [
      { t: "So: the same Thunderbolt 4.", e: "same", sw: 6 },
      { t: "The same 256 channels to the computer.", e: "256", sw: 10 },
      { t: "The same 64-channel mixer,", e: "64-channel", sw: 6 },
      { t: "26 aux buses,", e: "26", sw: 5 },
      { t: "running in the hardware", e: "in the hardware" },
      { t: "whether the computer is on or not.", e: "on or not", beat: true },
      { t: "The same CueMix Pro across all three.", e: "CueMix Pro", beat: true },
      { t: "Choose by the front panel.", e: "front panel", beat: true },
      { t: "Sixteen line inputs.", e: "Sixteen" },
      { t: "Four preamps. Or ten.", e: "Or ten", beat: true },
      { t: "Then let the switch", e: "the switch" },
      { t: "make them one system.", e: "one system", beat: true },
      { t: "MOTU AVB.", e: "MOTU AVB" },
      { t: "From Shivansh Electronics, Kolkata.", e: "Shivansh Electronics", beat: true },
    ],
  },
];

// ── Derived timing ───────────────────────────────────────────────────────────

/** Spoken word count for a caption — the `sw` override wins when numerals expand. */
export const spokenWords = (c: Caption): number =>
  c.sw ?? c.t.trim().split(/\s+/).length;

export type TimedCaption = Caption & {
  start: number;
  end: number;
  /** Index within its segment. */
  i: number;
};

export type TimedSegment = Omit<Segment, "captions"> & {
  start: number;
  end: number;
  words: number;
  captions: TimedCaption[];
};

/**
 * Lays every caption on an absolute timeline from its spoken length.
 * This is the audio-anchored pattern: no scene duration is ever estimated,
 * it is derived from how long the words take to say.
 */
export const buildTimeline = (): { segments: TimedSegment[]; total: number } => {
  let t = 0;
  const segments = SEGMENTS.map((seg) => {
    const start = t;
    let words = 0;
    const captions = seg.captions.map((c, i) => {
      const w = spokenWords(c);
      words += w;
      const dur = (w / WPM) * 60 + (c.beat ? BEAT : 0);
      const cap: TimedCaption = { ...c, i, start: t, end: t + dur };
      t += dur;
      return cap;
    });
    const end = t;
    t += SEGMENT_GAP;
    return { ...seg, start, end, words, captions };
  });
  return { segments, total: t - SEGMENT_GAP };
};
