// Asset registry, generated by scripts/build-manifest.mjs + copy-assets.mjs.
//
// Keyed by the stable index assigned during the mandatory visual inventory —
// NOT by filename. The supplied filename product prefixes are demonstrably
// unreliable: "MOTU 10pre (23).jpg", "MOTU 16A (3).jpg" and "MOTU 848 (6).jpg"
// are byte-identical to one another. Every image was classified by looking at
// it. `reel` records which of the three reels owns each image, so no image is
// used twice across the set and none is left without a home.
import { staticFile } from "remotion";
import manifest from "../asset-manifest.json";

export type Bucket = "10pre" | "16A" | "848" | "AVBSwitch" | "Network" | "Shared" | "Brand";

export type AssetEntry = {
  idx: number;
  file: string;
  aliases: string[];
  w: number;
  h: number;
  fmt: string;
  ar: number;
  product: Bucket;
  /** 1|2|3 for product images; 0 for the logos, which appear in all three. */
  reel: number;
  tier: "hero" | "support";
  slug: string;
  ext: string;
  /** Auto-detected from the image's own four corners at asset-copy time. */
  bg: "light" | "mixed" | "dark";
  border: number;
};

export const ASSETS = manifest as AssetEntry[];
const BY_IDX = new Map<number, AssetEntry>(ASSETS.map((a) => [a.idx, a]));

export function meta(idx: number): AssetEntry {
  const a = BY_IDX.get(idx);
  if (!a) throw new Error(`No asset with index ${idx}`);
  return a;
}
export function img(idx: number): string {
  const a = meta(idx);
  return staticFile(`images/${a.slug}.${a.ext}`);
}
export const ar = (idx: number): number => meta(idx).ar;

/** Every product image owned by a given reel. */
export const reelImages = (reel: number): number[] =>
  ASSETS.filter((a) => a.reel === reel).map((a) => a.idx);

export const LOGO = { motu: 121, shivansh: 122 } as const;

// ───────────────────────────────────────────────── Reel 1 — "The Source"
// MOTU 10pre + the shared-engine intro. 34 images.
export const TENPRE = {
  qFrontLeft: 39,       // hero — full macro-to-reveal
  qFrontRight: 38,
  qRearLeft: 37,
  qFrontLeftAlt: 41,
  qFrontDark: 40,
  frontElevation: 30,
  rearElevation: 35,    // port density sweep
  inserts: 5,           // macro-to-reveal
  combos4: 9,           // the hook
  meters: 7,
  metersWide: 15,
  lineOut: 16,
  rearIO: 17,
  headphones: 27,
  monitorGroup: 13,
  frontLineArt: 4,
  connectivity: 6,
  rtl: 8,
  rearCableFan: 1,
  ipad: 12,
  cuemixPatchbay: 3,
  cuemixDynamics: 28,
  cuemixEq: 29,
  cuemixHome: 32,
  cuemixMicIn: 33,
  cuemixMixing: 34,
  cuemixOutputs: 36,
} as const;

export const R1_SHARED = {
  ess: 24,
  thunderbolt: 26,
  studioWide: 14,
  usbC: 10,
  discovery: 31,
  cuemixMonitor: 11,
  topologyDaisy: 23,
} as const;

// ───────────────────────────────────────────────── Reel 2 — "The Matrix"
// MOTU 16A + software control. 50 images. (Populated when Reel 2 is built.)
export const S16A = {
  qFront: 79, qFrontRight: 80, qRear: 77, qRearRight: 78, qFrontDark: 81,
  frontElevation: 76, rearElevation: 51,
  wideFront: 45, wideFrontAlt: 47, wideFrontB: 49,
  meters: 58, rearOptical: 60, lineOutJacks: 62, rearCableFan: 63,
  networkOptical: 65, rearFull: 74, frontLineArt: 67, connectivity: 69, rtl: 71,
  deskLifestyle: 42, laptopLifestyle: 56, ipad: 73,
} as const;

// ───────────────────────────────────── Reel 3 — "The Command Center & Scale"
// MOTU 848 + AVB Switch + the network story. 36 images.
export const S848 = {
  qFront: 110, qFrontRight: 111, qRear: 108, qRearRight: 109, qFrontDark: 107,
  frontElevation: 85, rearElevation: 86,
  headphones: 88, lineOut: 89, rearCableFan: 90, rearIO: 91,
  insertsCombo: 93, meters: 94, metersAlt: 101, combos4: 95,
  monitorGroup: 97, speakerSelect: 18,
  frontLineArt: 103, connectivity: 104, rtl: 105, ipad: 106,
} as const;

export const AVBSW = { qWhite: 112, qPorts: 114, frontElevation: 116 } as const;

export const NET = {
  topologyDaisy: 23, topology16A: 68, topologyRender: 113,
  milan: 100, ieeeAvb: 115, rj45Cable: 117,
  clock: 118, qos: 119, gauge: 120,
} as const;

// ───────────────────────────────────────────────────────────────── audio
export const MUSIC = (slug: string): string => staticFile(`audio/music/${slug}.mp3`);
export const SFX = (name: string): string => staticFile(`audio/sfx/${name}.wav`);
export const VO = (reel: number): string => staticFile(`vo/voiceover-reel${reel}.mp3`);

export type SfxKey =
  | "encoder-detent" | "encoder-detent-hi" | "encoder-detent-lo" | "encoder-turn"
  | "rj45-snap" | "rj45-snap-soft" | "talkback-engage"
  | "relay-tick" | "relay-tick-hi" | "counter-tick" | "rack-seat"
  | "avb-ping-hi" | "avb-ping-mid" | "avb-ping-lo" | "avb-ping-top"
  | "gptp-sync" | "data-stream" | "data-stream-short" | "link-establish"
  | "panel-air" | "panel-air-soft";
