// CHECKPOINT 6 — branding cadence.
//
// Produces the timestamped list of every Shivansh Electronics appearance and
// every MOTU appearance, then enforces Section 7:
//   * no gap longer than ~34-40 s between Shivansh appearances
//   * every one of the seven chapters contains a Shivansh beat
//   * MOTU appears a handful of times INCLUDING mid-video, not only at the ends
//   * www.shivanshelectronics.in is the most-repeated single contact detail
import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { loadSchedule, PROJ } from "./_load.mjs";

const { BEATS, BEAT_STARTS, CHAPTERS, frames } = await loadSchedule();
const MAX_GAP_SEC = 40;

const tc = (f) => {
  const s = f / 30;
  return `${String(Math.floor(s / 60)).padStart(2, "0")}:${String(Math.floor(s % 60)).padStart(2, "0")}`;
};

/** What form the Shivansh presence takes in a beat, if any. */
function shivansh(b) {
  if (b.brand === "beat") return "full branding beat (logo + role + URL + contact)";
  if (b.brand === "corner" || b.brand === "cornerLeft") return "corner logo + URL";
  if (b.brand === "lower") return "lower-third logo + URL + region";
  if (b.kind === "contact") return "contact panel (logo + URL + socials + address)";
  if (b.kind === "outro") return "outro lockup (logo + URL + prices)";
  if (b.kind === "price") return "distributor line + dual price";
  if (b.kind === "coldOpen") return "distributor line";
  return null;
}
const motu = (b) => (b.motu ? "MOTU logo" : b.kind === "outro" ? "MOTU logo" : null);

const rows = BEATS.map((b, i) => ({
  b, i, start: BEAT_STARTS[i], end: BEAT_STARTS[i] + frames(b.sec),
  s: shivansh(b), m: motu(b),
}));

const sRows = rows.filter((r) => r.s);
const mRows = rows.filter((r) => r.m);

console.log("SHIVANSH ELECTRONICS — appearances");
let prevEnd = 0, worst = 0, worstAt = "";
const gaps = [];
for (const r of sRows) {
  const gap = (r.start - prevEnd) / 30;
  if (gap > worst) { worst = gap; worstAt = tc(prevEnd); }
  gaps.push(gap);
  console.log(
    `  ${tc(r.start)}–${tc(r.end)}  ch${r.b.ch}  ${r.b.id.padEnd(20)} ${r.s}` +
    (gap > 0.5 ? `   (gap ${gap.toFixed(0)}s)` : "")
  );
  prevEnd = Math.max(prevEnd, r.end);
}
const tailGap = (BEAT_STARTS[BEATS.length - 1] + frames(BEATS[BEATS.length - 1].sec) - prevEnd) / 30;

console.log(`\n  total appearances: ${sRows.length}`);
console.log(`  longest gap:       ${worst.toFixed(0)}s (starting ${worstAt})`);
console.log(`  trailing gap:      ${tailGap.toFixed(0)}s`);

console.log("\nMOTU — appearances");
for (const r of mRows) console.log(`  ${tc(r.start)}–${tc(r.end)}  ch${r.b.ch}  ${r.b.id.padEnd(20)} ${r.m}`);
console.log(`\n  total appearances: ${mRows.length}`);

// per-chapter presence
console.log("\nper-chapter Shivansh presence");
let everyChapter = true;
for (const c of CHAPTERS) {
  const n = sRows.filter((r) => r.b.ch === c.n).length;
  if (n === 0) everyChapter = false;
  console.log(`  ch${c.n} ${c.name.padEnd(26)} ${n} appearance${n === 1 ? "" : "s"}${n === 0 ? "   <-- MISSING" : ""}`);
}

// URL repetition — the website must lead every other single contact detail
const urlCount = sRows.filter((r) =>
  ["full branding beat (logo + role + URL + contact)", "corner logo + URL",
   "lower-third logo + URL + region", "contact panel (logo + URL + socials + address)",
   "outro lockup (logo + URL + prices)"].includes(r.s)
).length;
const socialCount = sRows.filter((r) => r.s.includes("socials")).length +
  BEATS.filter((b) => b.kind === "brandBeat").length; // brand beats list 3 socials once each

console.log(`\nwww.shivanshelectronics.in on-screen appearances: ${urlCount}`);
console.log(`next most-repeated single detail (socials):        ${socialCount}`);

const gapOk = worst <= MAX_GAP_SEC && tailGap <= MAX_GAP_SEC;
const motuOk = mRows.length >= 5 && mRows.some((r) => r.b.ch >= 3 && r.b.ch <= 6);
const urlOk = urlCount > socialCount;

console.log("\nchecks");
console.log(`  ${gapOk ? "ok  " : "FAIL"} no Shivansh gap over ${MAX_GAP_SEC}s`);
console.log(`  ${everyChapter ? "ok  " : "FAIL"} every chapter has a Shivansh beat`);
console.log(`  ${motuOk ? "ok  " : "FAIL"} MOTU present a handful of times incl. mid-video`);
console.log(`  ${urlOk ? "ok  " : "FAIL"} website is the most-repeated single detail`);

writeFileSync(
  resolve(PROJ, "BRANDING_CADENCE.md"),
  `# Branding cadence — MOTU AVB Ecosystem long-form

Generated by \`npm run branding\` from the same schedule that renders the video.

Every logo appearance renders through the \`Logo\` component, which draws the
supplied logo file exactly as given — opaque, with its own white background
intact, never alpha-keyed — **directly on the video with no box, card or
plate**. The page palette is held in a near-white range so that white ground
reads as continuous with it; the full-frame branding beats additionally use a
flat page (\`Ground flat\`) so nothing shows an edge behind the artwork.

## Shivansh Electronics — ${sRows.length} appearances (longest gap ${worst.toFixed(0)}s)

| In | Out | Chapter | Beat | Form |
|---|---|---|---|---|
${sRows.map((r) => `| ${tc(r.start)} | ${tc(r.end)} | ${r.b.ch} | \`${r.b.id}\` | ${r.s} |`).join("\n")}

## MOTU — ${mRows.length} appearances

| In | Out | Chapter | Beat |
|---|---|---|---|
${mRows.map((r) => `| ${tc(r.start)} | ${tc(r.end)} | ${r.b.ch} | \`${r.b.id}\` |`).join("\n")}

## Result

- Longest gap between Shivansh appearances: **${worst.toFixed(0)}s** (guideline ≤ ${MAX_GAP_SEC}s)
- Trailing gap to end of video: **${tailGap.toFixed(0)}s**
- Chapters containing a Shivansh beat: **${CHAPTERS.filter((c) => sRows.some((r) => r.b.ch === c.n)).length}/7**
- \`www.shivanshelectronics.in\` on-screen: **${urlCount}** — more than any other single contact detail
`
);
console.log("\nwrote BRANDING_CADENCE.md");
const pass = gapOk && everyChapter && motuOk && urlOk;
console.log(pass ? "BRANDING: PASS" : "BRANDING: FAIL");
process.exit(pass ? 0 : 1);
