#!/usr/bin/env node
// Generates ASSET_COVERAGE_EXPLAINER_REEL.md — the mandatory coverage proof
// (brief Section 5: "produce an explicit list of every distinct image used per
// product, mapped to its timeline placement, and confirm full coverage across
// all four products/devices before considering the build complete").
//
// It reads the SAME shot plan the video renders from, so it cannot drift from
// what is actually on screen. If an image is not in a shot, it is not in this
// ledger either, and the script exits non-zero.
//
// Run: node --experimental-strip-types scripts/coverage.mjs
import { writeFileSync, readdirSync } from "node:fs";
import { ASSETS, REPO_FILE_COUNT, EXCLUDED_COUNT } from "../src/assets.ts";
import { buildShots } from "../src/shots.ts";
import { ACCENT } from "../src/theme.ts";

const { shots } = buildShots();

const ts = (s) =>
  `${String(Math.floor(s / 60)).padStart(2, "0")}:${(s % 60).toFixed(1).padStart(4, "0")}`;

// Where each image appears.
const placement = new Map(); // slug -> [{ start, kind, segment, reprise }]
for (const s of shots) {
  for (const a of s.assets) {
    if (!placement.has(a.slug)) placement.set(a.slug, []);
    placement.get(a.slug).push({ start: s.start, kind: s.kind, segment: s.segment, reprise: !!s.reprise });
  }
}

const PRODUCTS = [
  ["p16a", "MOTU 16A"],
  ["p848", "MOTU 848"],
  ["p10pre", "MOTU 10pre"],
  ["pswitch", "MOTU AVB Switch"],
  ["shared", "Shared platform"],
];

const SEG_NAME = {
  open: "Cold open",
  s16a: "16A",
  s848: "848",
  s10pre: "10pre",
  sswitch: "AVB Switch",
  close: "Close",
};

const TIER = {
  hero: "**HERO** — its own staged moment",
  pair: "**PAIR** — front/rear panel run",
  strip: "**STRIP** — legible plate in a short run",
  grid: "**GRID** — cell in an assembling board",
};

const missing = ASSETS.filter((a) => !placement.has(a.slug));
const coveredFiles = ASSETS.reduce((n, a) => n + a.covers.length, 0);

let md = `# ASSET COVERAGE — MOTU AVB Ecosystem narrated explainer reel

Auto-generated by \`scripts/coverage.mjs\` from the same shot plan the video is
rendered from (\`src/shots.ts\`). It is not maintained by hand and cannot
disagree with what is on screen.

**Deliverable:** \`explainer-reel\` — 180.000 s / 2160 × 3840 / 30 fps
This ledger is for THIS reel only. The three-part series' own ledger
(\`../ASSET_COVERAGE.md\`) is untouched.

## Headline

| | |
|---|---|
| Product image files in the repository root | **${REPO_FILE_COUNT}** |
| Content-verified exclusions | **${EXCLUDED_COUNT}** (covering 4 filenames) |
| Byte-identical duplicate filenames collapsed | **${coveredFiles - ASSETS.length}** |
| **Distinct images requiring coverage** | **${ASSETS.length}** |
| **Distinct images placed on the timeline** | **${placement.size}** |
| **Not placed** | **${missing.length}** |
| Original filenames satisfied | **${coveredFiles} + 4 excluded = ${coveredFiles + 4}** |

${missing.length === 0 ? "**Coverage is complete.** Every distinct image in the repository appears in the reel." : `**INCOMPLETE — ${missing.length} images unplaced.**`}

## How the count reconciles to ${REPO_FILE_COUNT} files

The repository root holds ${REPO_FILE_COUNT} files matching the four product name patterns, but
they are not ${REPO_FILE_COUNT} different photographs. ${coveredFiles - ASSETS.length} of them are byte-identical to
another file saved under a different product's name, and 4 more are not usable
product imagery at all. Deduplicating by content hash rather than by filename
gives ${ASSETS.length} distinct images, and those ${ASSETS.length} images satisfy all ${coveredFiles} valid filenames
(${ASSETS.length} + ${coveredFiles - ASSETS.length} collapsed + 4 excluded = ${REPO_FILE_COUNT}).

**Why dedupe at all.** Showing one photograph twice under two different product
labels would directly contradict the product-identification discipline the brief
makes mandatory (Section 4). Every one of the cross-product duplicates
turned out to be a *shared platform* asset — CueMix Pro screens, the DSP reverb
window, the ESS and Thunderbolt marks, the bundled cable, DAW windows, rear-panel
network detail. They are duplicated across product folders precisely because they
belong to all of them, which makes them the reel's own evidence for its
"same platform underneath" thesis. They are re-homed to a \`shared\` pool and
bookend the film: the claim in the cold open, the proof in the close.

### Content-verified exclusions

| File(s) | Why excluded |
|---|---|
| \`MOTU 10pre (23).jpg\`, \`MOTU 16A (3).jpg\`, \`MOTU 848 (6).jpg\` | One photograph of a **Moog modular synthesiser**, saved under three MOTU product filenames. No MOTU hardware, software or context appears in it. Re-confirmed for this build by inspecting the image rather than trusting the filename. |
| \`MOTU AVB SWITCH (2).png\` | A 2 KB flat grey rectangle — not a photograph of anything. On screen it would read as a broken asset. |

## Coverage by product

| Product | Distinct images | Placed | Remaining | Accent |
|---|---|---|---|---|
`;

for (const [key, name] of PRODUCTS) {
  const items = ASSETS.filter((a) => a.product === key);
  const done = items.filter((a) => placement.has(a.slug)).length;
  md += `| ${name} | ${items.length} | ${done} | ${items.length - done} | \`${ACCENT[key].key}\` |\n`;
}

md += `
## Tiers

| Tier | What it means on screen |
|---|---|
| **HERO** | One image, staged photo-real with its own cast shadow — the image a sentence rests on |
| **PAIR** | Two panel runs stacked, front above rear |
| **STRIP** | Three or fewer plates in a run, each large enough to read |
| **GRID** | A board of 4–8 cells that assembles over ~1 s and then holds. Not a burst of cuts — one composition |

A grid cell is not a lesser placement: at 2160 px wide a three-column grid gives
~640 px cells, which is large enough to read a connector row. The tier system is
how 119 images fit into 180 seconds without the reel becoming the fast-cut
montage it is explicitly not meant to be.

## Subjects

Every image was classified by what it actually shows, because the alpha channel
does not tell you: the CueMix Pro roundel, the Thunderbolt mark and the
round-trip-latency diagram are all transparent PNGs. Hero slots are drawn from
hardware (and, in the AVB Switch segment, from diagrams — its subject is a
network, not a box). Software screens, logos and bundled-content artwork are all
still used, in the grid tier.

| Subject | Count | Eligible for a hero slot |
|---|---|---|
`;
const subs = {};
for (const a of ASSETS) subs[a.subject] = (subs[a.subject] || 0) + 1;
const heroOK = { hardware: "yes", diagram: "yes (AVB Switch)", context: "no", ui: "no", mark: "no", bundle: "no" };
for (const [k, v] of Object.entries(subs).sort((a, b) => b[1] - a[1])) {
  md += `| ${k} | ${v} | ${heroOK[k] ?? "no"} |\n`;
}

md += `\n## Full ledger\n\nOrdered by first appearance on the timeline.\n\n`;
md += `| # | First seen | Segment | Tier | Image | Subject | Original filename(s) satisfied |\n`;
md += `|---|---|---|---|---|---|---|\n`;

const rows = ASSETS.map((a) => {
  const ps = (placement.get(a.slug) ?? []).slice().sort((x, y) => x.start - y.start);
  return { a, ps, first: ps.length ? ps[0].start : Infinity };
}).sort((x, y) => x.first - y.first || x.a.slug.localeCompare(y.a.slug));

rows.forEach((r, i) => {
  const p = r.ps[0];
  const extra = r.ps.length > 1 ? ` _(+${r.ps.length - 1} more)_` : "";
  md += `| ${i + 1} | \`${p ? ts(p.start) : "—"}\`${extra} | ${p ? SEG_NAME[p.segment] : "—"} | ${p ? p.kind.toUpperCase() : "—"} | \`${r.a.file}\` | ${r.a.subject} | ${r.a.covers.map((c) => `\`${c}\``).join("<br>")} |\n`;
});

md += `
## Reprises

The cold open and the close both show all four products together — the open
because it names them in its first ten seconds, the close because the whole film
resolves on them being one system. Those are the only images that appear twice,
and they are covered properly inside their own product segments:

| Image | Reprised at | Covered at |
|---|---|---|
`;
for (const [slug, ps] of placement) {
  if (ps.length > 1 && ps.some((p) => p.reprise)) {
    const rep = ps.filter((p) => p.reprise).map((p) => ts(p.start)).join(", ");
    const own = ps.filter((p) => !p.reprise).map((p) => `${ts(p.start)} (${SEG_NAME[p.segment]})`).join(", ");
    md += `| \`${slug}\` | ${rep} | ${own || "—"} |\n`;
  }
}

md += `\n---\n\n_Generated ${new Date().toISOString().slice(0, 10)} from \`src/shots.ts\`._\n`;

writeFileSync("../ASSET_COVERAGE_EXPLAINER_REEL.md", md);

console.log(
  `ASSET_COVERAGE_EXPLAINER_REEL.md — ${placement.size}/${ASSETS.length} distinct images placed, ` +
    `${coveredFiles} + 4 excluded = ${coveredFiles + 4} of ${REPO_FILE_COUNT} filenames accounted for`,
);
if (missing.length) {
  console.error(`COVERAGE INCOMPLETE — ${missing.length} unplaced: ${missing.map((a) => a.slug).join(", ")}`);
  process.exit(1);
}
