// AUTO-GENERATED by scripts/prep-assets.mjs — do not edit by hand.
// 119 distinct images from 139 files in the repository root
// (18 byte-identical duplicates collapsed, 2 content-excluded).
//
// kind:    cutout (transparent) | strip (transparent ultra-wide panel run) | panel (opaque ultra-wide) | photo
// subject: hardware | detail | context | ui | diagram | mark | bundle
// `covers` lists every original repository filename this one image satisfies.

export type AssetKind = "cutout" | "strip" | "panel" | "photo";
export type AssetSubject = "hardware" | "detail" | "context" | "ui" | "diagram" | "mark" | "bundle";
export type ProductKey = "p16a" | "p848" | "p10pre" | "pswitch" | "shared";

export type Asset = {
  slug: string;
  file: string;
  /** A 512 px copy, for the darkened wash behind a full-bleed shot. */
  bg: string;
  product: ProductKey;
  w: number;
  h: number;
  ar: number;
  kind: AssetKind;
  subject: AssetSubject;
  alpha: boolean;
  covers: string[];
};

export const ASSETS: Asset[] = [
 {
  "slug": "motu-10pre-1-jpg",
  "file": "motu-10pre-1-jpg.jpg",
  "bg": "bg/motu-10pre-1-jpg.jpg",
  "product": "p10pre",
  "w": 3000,
  "h": 1780,
  "ar": 1.685,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 10pre (1).jpg"
  ]
 },
 {
  "slug": "motu-10pre-1-png",
  "file": "motu-10pre-1-png.png",
  "bg": "bg/motu-10pre-1-png.jpg",
  "product": "p10pre",
  "w": 2516,
  "h": 1415,
  "ar": 1.778,
  "kind": "cutout",
  "subject": "ui",
  "alpha": true,
  "covers": [
   "MOTU 10pre (1).png"
  ]
 },
 {
  "slug": "motu-10pre-10-jpg",
  "file": "motu-10pre-10-jpg.jpg",
  "bg": "bg/motu-10pre-10-jpg.jpg",
  "product": "p10pre",
  "w": 2906,
  "h": 1842,
  "ar": 1.578,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 10pre (10).jpg"
  ]
 },
 {
  "slug": "motu-10pre-10-png",
  "file": "motu-10pre-10-png.png",
  "bg": "bg/motu-10pre-10-png.jpg",
  "product": "p10pre",
  "w": 1773,
  "h": 531,
  "ar": 3.339,
  "kind": "cutout",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 10pre (10).png"
  ]
 },
 {
  "slug": "motu-10pre-11-jpg",
  "file": "motu-10pre-11-jpg.jpg",
  "bg": "bg/motu-10pre-11-jpg.jpg",
  "product": "p10pre",
  "w": 1038,
  "h": 629,
  "ar": 1.65,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 10pre (11).jpg"
  ]
 },
 {
  "slug": "motu-10pre-11-png",
  "file": "motu-10pre-11-png.png",
  "bg": "bg/motu-10pre-11-png.jpg",
  "product": "p10pre",
  "w": 1833,
  "h": 803,
  "ar": 2.283,
  "kind": "cutout",
  "subject": "diagram",
  "alpha": true,
  "covers": [
   "MOTU 10pre (11).png"
  ]
 },
 {
  "slug": "motu-10pre-12-jpg",
  "file": "motu-10pre-12-jpg.jpg",
  "bg": "bg/motu-10pre-12-jpg.jpg",
  "product": "p10pre",
  "w": 1522,
  "h": 485,
  "ar": 3.138,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 10pre (12).jpg"
  ]
 },
 {
  "slug": "motu-10pre-12-png",
  "file": "motu-10pre-12-png.png",
  "bg": "bg/motu-10pre-12-png.jpg",
  "product": "p10pre",
  "w": 399,
  "h": 627,
  "ar": 0.636,
  "kind": "cutout",
  "subject": "diagram",
  "alpha": true,
  "covers": [
   "MOTU 10pre (12).png"
  ]
 },
 {
  "slug": "motu-10pre-13-jpg",
  "file": "motu-10pre-13-jpg.jpg",
  "bg": "bg/motu-10pre-13-jpg.jpg",
  "product": "p10pre",
  "w": 1038,
  "h": 629,
  "ar": 1.65,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 10pre (13).jpg"
  ]
 },
 {
  "slug": "motu-10pre-13-png",
  "file": "motu-10pre-13-png.png",
  "bg": "bg/motu-10pre-13-png.jpg",
  "product": "p10pre",
  "w": 756,
  "h": 703,
  "ar": 1.075,
  "kind": "cutout",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 10pre (13).png"
  ]
 },
 {
  "slug": "motu-10pre-14-jpg",
  "file": "motu-10pre-14-jpg.jpg",
  "bg": "bg/motu-10pre-14-jpg.jpg",
  "product": "p10pre",
  "w": 3000,
  "h": 2008,
  "ar": 1.494,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 10pre (14).jpg"
  ]
 },
 {
  "slug": "motu-10pre-14-png",
  "file": "motu-10pre-14-png.png",
  "bg": "bg/motu-10pre-14-png.jpg",
  "product": "p10pre",
  "w": 945,
  "h": 560,
  "ar": 1.688,
  "kind": "cutout",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 10pre (14).png"
  ]
 },
 {
  "slug": "motu-10pre-15-jpg",
  "file": "motu-10pre-15-jpg.jpg",
  "bg": "bg/motu-10pre-15-jpg.jpg",
  "product": "p10pre",
  "w": 2000,
  "h": 714,
  "ar": 2.801,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 10pre (15).jpg"
  ]
 },
 {
  "slug": "motu-10pre-16-jpg",
  "file": "motu-10pre-16-jpg.jpg",
  "bg": "bg/motu-10pre-16-jpg.jpg",
  "product": "p10pre",
  "w": 1000,
  "h": 519,
  "ar": 1.927,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU 10pre (16).jpg"
  ]
 },
 {
  "slug": "motu-10pre-17-jpg",
  "file": "motu-10pre-17-jpg.jpg",
  "bg": "bg/motu-10pre-17-jpg.jpg",
  "product": "p10pre",
  "w": 2000,
  "h": 1083,
  "ar": 1.847,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 10pre (17).jpg"
  ]
 },
 {
  "slug": "motu-10pre-18-jpg",
  "file": "motu-10pre-18-jpg.jpg",
  "bg": "bg/motu-10pre-18-jpg.jpg",
  "product": "p10pre",
  "w": 2000,
  "h": 1188,
  "ar": 1.684,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 10pre (18).jpg"
  ]
 },
 {
  "slug": "motu-10pre-2-jpg",
  "file": "motu-10pre-2-jpg.jpg",
  "bg": "bg/motu-10pre-2-jpg.jpg",
  "product": "p10pre",
  "w": 2000,
  "h": 1083,
  "ar": 1.847,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 10pre (2).jpg"
  ]
 },
 {
  "slug": "motu-10pre-25-jpg",
  "file": "motu-10pre-25-jpg.jpg",
  "bg": "bg/motu-10pre-25-jpg.jpg",
  "product": "p10pre",
  "w": 3000,
  "h": 2414,
  "ar": 1.243,
  "kind": "photo",
  "subject": "diagram",
  "alpha": false,
  "covers": [
   "MOTU 10pre (25).jpg"
  ]
 },
 {
  "slug": "motu-10pre-29-jpg",
  "file": "motu-10pre-29-jpg.jpg",
  "bg": "bg/motu-10pre-29-jpg.jpg",
  "product": "p10pre",
  "w": 992,
  "h": 606,
  "ar": 1.637,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 10pre (29).jpg"
  ]
 },
 {
  "slug": "motu-10pre-3-jpg",
  "file": "motu-10pre-3-jpg.jpg",
  "bg": "bg/motu-10pre-3-jpg.jpg",
  "product": "p10pre",
  "w": 2880,
  "h": 1842,
  "ar": 1.564,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 10pre (3).jpg"
  ]
 },
 {
  "slug": "motu-10pre-4-jpg",
  "file": "motu-10pre-4-jpg.jpg",
  "bg": "bg/motu-10pre-4-jpg.jpg",
  "product": "p10pre",
  "w": 2880,
  "h": 1842,
  "ar": 1.564,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 10pre (4).jpg"
  ]
 },
 {
  "slug": "motu-10pre-4-png",
  "file": "motu-10pre-4-png.png",
  "bg": "bg/motu-10pre-4-png.jpg",
  "product": "p10pre",
  "w": 3000,
  "h": 466,
  "ar": 6.438,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 10pre (4).png"
  ]
 },
 {
  "slug": "motu-10pre-5-jpg",
  "file": "motu-10pre-5-jpg.jpg",
  "bg": "bg/motu-10pre-5-jpg.jpg",
  "product": "p10pre",
  "w": 2132,
  "h": 1615,
  "ar": 1.32,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 10pre (5).jpg"
  ]
 },
 {
  "slug": "motu-10pre-6-jpg",
  "file": "motu-10pre-6-jpg.jpg",
  "bg": "bg/motu-10pre-6-jpg.jpg",
  "product": "p10pre",
  "w": 2638,
  "h": 3000,
  "ar": 0.879,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 10pre (6).jpg"
  ]
 },
 {
  "slug": "motu-10pre-7-jpg",
  "file": "motu-10pre-7-jpg.jpg",
  "bg": "bg/motu-10pre-7-jpg.jpg",
  "product": "p10pre",
  "w": 2660,
  "h": 2305,
  "ar": 1.154,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 10pre (7).jpg"
  ]
 },
 {
  "slug": "motu-10pre-8-jpg",
  "file": "motu-10pre-8-jpg.jpg",
  "bg": "bg/motu-10pre-8-jpg.jpg",
  "product": "p10pre",
  "w": 2870,
  "h": 1826,
  "ar": 1.572,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 10pre (8).jpg"
  ]
 },
 {
  "slug": "motu-10pre-8-png",
  "file": "motu-10pre-8-png.png",
  "bg": "bg/motu-10pre-8-png.jpg",
  "product": "p10pre",
  "w": 3000,
  "h": 505,
  "ar": 5.941,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 10pre (8).png"
  ]
 },
 {
  "slug": "motu-10pre-9-jpg",
  "file": "motu-10pre-9-jpg.jpg",
  "bg": "bg/motu-10pre-9-jpg.jpg",
  "product": "p10pre",
  "w": 2660,
  "h": 2751,
  "ar": 0.967,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 10pre (9).jpg"
  ]
 },
 {
  "slug": "motu-10pre-newly-added-1-png",
  "file": "motu-10pre-newly-added-1-png.png",
  "bg": "bg/motu-10pre-newly-added-1-png.jpg",
  "product": "p10pre",
  "w": 3000,
  "h": 716,
  "ar": 4.19,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 10PRE NEWLY ADDED (1).png"
  ]
 },
 {
  "slug": "motu-10pre-newly-added-2-png",
  "file": "motu-10pre-newly-added-2-png.png",
  "bg": "bg/motu-10pre-newly-added-2-png.jpg",
  "product": "p10pre",
  "w": 3000,
  "h": 744,
  "ar": 4.032,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 10PRE NEWLY ADDED (2).png"
  ]
 },
 {
  "slug": "motu-10pre-newly-added-3-png",
  "file": "motu-10pre-newly-added-3-png.png",
  "bg": "bg/motu-10pre-newly-added-3-png.jpg",
  "product": "p10pre",
  "w": 3000,
  "h": 771,
  "ar": 3.891,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 10PRE NEWLY ADDED (3).png"
  ]
 },
 {
  "slug": "motu-10pre-newly-added-jpg",
  "file": "motu-10pre-newly-added-jpg.jpg",
  "bg": "bg/motu-10pre-newly-added-jpg.jpg",
  "product": "p10pre",
  "w": 3000,
  "h": 1366,
  "ar": 2.196,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU 10PRE NEWLY ADDED.jpg"
  ]
 },
 {
  "slug": "motu-10pre-newly-added-png",
  "file": "motu-10pre-newly-added-png.png",
  "bg": "bg/motu-10pre-newly-added-png.jpg",
  "product": "p10pre",
  "w": 3000,
  "h": 735,
  "ar": 4.082,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 10PRE NEWLY ADDED.png"
  ]
 },
 {
  "slug": "motu-16a-1-jpg",
  "file": "motu-16a-1-jpg.jpg",
  "bg": "bg/motu-16a-1-jpg.jpg",
  "product": "p16a",
  "w": 3000,
  "h": 1384,
  "ar": 2.168,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU 16A (1).jpg"
  ]
 },
 {
  "slug": "motu-16a-1-png",
  "file": "motu-16a-1-png.png",
  "bg": "bg/motu-16a-1-png.jpg",
  "product": "p16a",
  "w": 1024,
  "h": 1024,
  "ar": 1,
  "kind": "cutout",
  "subject": "mark",
  "alpha": true,
  "covers": [
   "MOTU 16A (1).png"
  ]
 },
 {
  "slug": "motu-16a-10-jpg",
  "file": "motu-16a-10-jpg.jpg",
  "bg": "bg/motu-16a-10-jpg.jpg",
  "product": "p16a",
  "w": 2870,
  "h": 1836,
  "ar": 1.563,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 16A (10).jpg"
  ]
 },
 {
  "slug": "motu-16a-10-png",
  "file": "motu-16a-10-png.png",
  "bg": "bg/motu-16a-10-png.jpg",
  "product": "p16a",
  "w": 3000,
  "h": 298,
  "ar": 10.067,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 16A (10).png"
  ]
 },
 {
  "slug": "motu-16a-11-jpg",
  "file": "motu-16a-11-jpg.jpg",
  "bg": "bg/motu-16a-11-jpg.jpg",
  "product": "p16a",
  "w": 2870,
  "h": 1836,
  "ar": 1.563,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 16A (11).jpg"
  ]
 },
 {
  "slug": "motu-16a-11-png",
  "file": "motu-16a-11-png.png",
  "bg": "bg/motu-16a-11-png.jpg",
  "product": "p16a",
  "w": 3000,
  "h": 298,
  "ar": 10.067,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 16A (11).png"
  ]
 },
 {
  "slug": "motu-16a-12-jpg",
  "file": "motu-16a-12-jpg.jpg",
  "bg": "bg/motu-16a-12-jpg.jpg",
  "product": "p16a",
  "w": 3000,
  "h": 2008,
  "ar": 1.494,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 16A (12).jpg"
  ]
 },
 {
  "slug": "motu-16a-12-png",
  "file": "motu-16a-12-png.png",
  "bg": "bg/motu-16a-12-png.jpg",
  "product": "p16a",
  "w": 3000,
  "h": 298,
  "ar": 10.067,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 16A (12).png"
  ]
 },
 {
  "slug": "motu-16a-13-jpg",
  "file": "motu-16a-13-jpg.jpg",
  "bg": "bg/motu-16a-13-jpg.jpg",
  "product": "p16a",
  "w": 2870,
  "h": 1836,
  "ar": 1.563,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 16A (13).jpg"
  ]
 },
 {
  "slug": "motu-16a-13-png",
  "file": "motu-16a-13-png.png",
  "bg": "bg/motu-16a-13-png.jpg",
  "product": "p16a",
  "w": 3000,
  "h": 508,
  "ar": 5.906,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 16A (13).png"
  ]
 },
 {
  "slug": "motu-16a-14-jpg",
  "file": "motu-16a-14-jpg.jpg",
  "bg": "bg/motu-16a-14-jpg.jpg",
  "product": "p16a",
  "w": 2956,
  "h": 2134,
  "ar": 1.385,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 16A (14).jpg"
  ]
 },
 {
  "slug": "motu-16a-15-jpg",
  "file": "motu-16a-15-jpg.jpg",
  "bg": "bg/motu-16a-15-jpg.jpg",
  "product": "p16a",
  "w": 2870,
  "h": 1836,
  "ar": 1.563,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 16A (15).jpg"
  ]
 },
 {
  "slug": "motu-16a-16-jpg",
  "file": "motu-16a-16-jpg.jpg",
  "bg": "bg/motu-16a-16-jpg.jpg",
  "product": "p16a",
  "w": 2413,
  "h": 2263,
  "ar": 1.066,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 16A (16).jpg"
  ]
 },
 {
  "slug": "motu-16a-17-jpg",
  "file": "motu-16a-17-jpg.jpg",
  "bg": "bg/motu-16a-17-jpg.jpg",
  "product": "p16a",
  "w": 2974,
  "h": 1836,
  "ar": 1.62,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 16A (17).jpg"
  ]
 },
 {
  "slug": "motu-16a-18-jpg",
  "file": "motu-16a-18-jpg.jpg",
  "bg": "bg/motu-16a-18-jpg.jpg",
  "product": "p16a",
  "w": 2509,
  "h": 2166,
  "ar": 1.158,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU 16A (18).jpg"
  ]
 },
 {
  "slug": "motu-16a-2-jpg",
  "file": "motu-16a-2-jpg.jpg",
  "bg": "bg/motu-16a-2-jpg.jpg",
  "product": "p16a",
  "w": 2000,
  "h": 900,
  "ar": 2.222,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU 16A (2).jpg"
  ]
 },
 {
  "slug": "motu-16a-21-jpg",
  "file": "motu-16a-21-jpg.jpg",
  "bg": "bg/motu-16a-21-jpg.jpg",
  "product": "p16a",
  "w": 2000,
  "h": 900,
  "ar": 2.222,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU 16A (21).jpg"
  ]
 },
 {
  "slug": "motu-16a-24-jpg",
  "file": "motu-16a-24-jpg.jpg",
  "bg": "bg/motu-16a-24-jpg.jpg",
  "product": "p16a",
  "w": 2000,
  "h": 1188,
  "ar": 1.684,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 16A (24).jpg"
  ]
 },
 {
  "slug": "motu-16a-25-jpg",
  "file": "motu-16a-25-jpg.jpg",
  "bg": "bg/motu-16a-25-jpg.jpg",
  "product": "p16a",
  "w": 3000,
  "h": 2094,
  "ar": 1.433,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 16A (25).jpg"
  ]
 },
 {
  "slug": "motu-16a-26-jpg",
  "file": "motu-16a-26-jpg.jpg",
  "bg": "bg/motu-16a-26-jpg.jpg",
  "product": "p16a",
  "w": 2520,
  "h": 1415,
  "ar": 1.781,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 16A (26).jpg",
   "MOTU 16A (27).jpg"
  ]
 },
 {
  "slug": "motu-16a-28-jpg",
  "file": "motu-16a-28-jpg.jpg",
  "bg": "bg/motu-16a-28-jpg.jpg",
  "product": "p16a",
  "w": 2000,
  "h": 1188,
  "ar": 1.684,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 16A (28).jpg"
  ]
 },
 {
  "slug": "motu-16a-4-png",
  "file": "motu-16a-4-png.png",
  "bg": "bg/motu-16a-4-png.jpg",
  "product": "p16a",
  "w": 1691,
  "h": 315,
  "ar": 5.368,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 16A (4).png"
  ]
 },
 {
  "slug": "motu-16a-5-png",
  "file": "motu-16a-5-png.png",
  "bg": "bg/motu-16a-5-png.jpg",
  "product": "p16a",
  "w": 1751,
  "h": 768,
  "ar": 2.28,
  "kind": "cutout",
  "subject": "diagram",
  "alpha": true,
  "covers": [
   "MOTU 16A (5).png"
  ]
 },
 {
  "slug": "motu-16a-6-jpg",
  "file": "motu-16a-6-jpg.jpg",
  "bg": "bg/motu-16a-6-jpg.jpg",
  "product": "p16a",
  "w": 2132,
  "h": 1615,
  "ar": 1.32,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 16A (6).jpg"
  ]
 },
 {
  "slug": "motu-16a-6-png",
  "file": "motu-16a-6-png.png",
  "bg": "bg/motu-16a-6-png.jpg",
  "product": "p16a",
  "w": 572,
  "h": 617,
  "ar": 0.927,
  "kind": "cutout",
  "subject": "diagram",
  "alpha": true,
  "covers": [
   "MOTU 16A (6).png"
  ]
 },
 {
  "slug": "motu-16a-7-jpg",
  "file": "motu-16a-7-jpg.jpg",
  "bg": "bg/motu-16a-7-jpg.jpg",
  "product": "p16a",
  "w": 2870,
  "h": 1836,
  "ar": 1.563,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 16A (7).jpg"
  ]
 },
 {
  "slug": "motu-16a-7-png",
  "file": "motu-16a-7-png.png",
  "bg": "bg/motu-16a-7-png.jpg",
  "product": "p16a",
  "w": 945,
  "h": 792,
  "ar": 1.193,
  "kind": "cutout",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 16A (7).png"
  ]
 },
 {
  "slug": "motu-16a-9-jpg",
  "file": "motu-16a-9-jpg.jpg",
  "bg": "bg/motu-16a-9-jpg.jpg",
  "product": "p16a",
  "w": 2870,
  "h": 2144,
  "ar": 1.339,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU 16A (9).jpg"
  ]
 },
 {
  "slug": "motu-16a-9-png",
  "file": "motu-16a-9-png.png",
  "bg": "bg/motu-16a-9-png.jpg",
  "product": "p16a",
  "w": 3000,
  "h": 466,
  "ar": 6.438,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 16A (9).png"
  ]
 },
 {
  "slug": "motu-16a-newly-added-1-png",
  "file": "motu-16a-newly-added-1-png.png",
  "bg": "bg/motu-16a-newly-added-1-png.jpg",
  "product": "p16a",
  "w": 3000,
  "h": 744,
  "ar": 4.032,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 16A NEWLY ADDED (1).png"
  ]
 },
 {
  "slug": "motu-16a-newly-added-2-png",
  "file": "motu-16a-newly-added-2-png.png",
  "bg": "bg/motu-16a-newly-added-2-png.jpg",
  "product": "p16a",
  "w": 3000,
  "h": 716,
  "ar": 4.19,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 16A NEWLY ADDED (2).png"
  ]
 },
 {
  "slug": "motu-16a-newly-added-3-png",
  "file": "motu-16a-newly-added-3-png.png",
  "bg": "bg/motu-16a-newly-added-3-png.jpg",
  "product": "p16a",
  "w": 3000,
  "h": 771,
  "ar": 3.891,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 16A NEWLY ADDED (3).png"
  ]
 },
 {
  "slug": "motu-16a-newly-added-4-png",
  "file": "motu-16a-newly-added-4-png.png",
  "bg": "bg/motu-16a-newly-added-4-png.jpg",
  "product": "p16a",
  "w": 3000,
  "h": 735,
  "ar": 4.082,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 16A NEWLY ADDED (4).png"
  ]
 },
 {
  "slug": "motu-16a-newly-added-jpg",
  "file": "motu-16a-newly-added-jpg.jpg",
  "bg": "bg/motu-16a-newly-added-jpg.jpg",
  "product": "p16a",
  "w": 3000,
  "h": 1366,
  "ar": 2.196,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU 16A NEWLY ADDED.jpg"
  ]
 },
 {
  "slug": "motu-10pre-20-jpg",
  "file": "motu-10pre-20-jpg.jpg",
  "bg": "bg/motu-10pre-20-jpg.jpg",
  "product": "p848",
  "w": 423,
  "h": 481,
  "ar": 0.879,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 10pre (20).jpg",
   "MOTU 848 (19).jpg"
  ]
 },
 {
  "slug": "motu-848-1-jpg",
  "file": "motu-848-1-jpg.jpg",
  "bg": "bg/motu-848-1-jpg.jpg",
  "product": "p848",
  "w": 1000,
  "h": 519,
  "ar": 1.927,
  "kind": "photo",
  "subject": "context",
  "alpha": false,
  "covers": [
   "MOTU 848 (1).jpg"
  ]
 },
 {
  "slug": "motu-848-1-png",
  "file": "motu-848-1-png.png",
  "bg": "bg/motu-848-1-png.jpg",
  "product": "p848",
  "w": 1024,
  "h": 1024,
  "ar": 1,
  "kind": "cutout",
  "subject": "mark",
  "alpha": true,
  "covers": [
   "MOTU 848 (1).png"
  ]
 },
 {
  "slug": "motu-848-10-jpg",
  "file": "motu-848-10-jpg.jpg",
  "bg": "bg/motu-848-10-jpg.jpg",
  "product": "p848",
  "w": 1149,
  "h": 1186,
  "ar": 0.969,
  "kind": "photo",
  "subject": "bundle",
  "alpha": false,
  "covers": [
   "MOTU 848 (10).jpg"
  ]
 },
 {
  "slug": "motu-848-11-jpg",
  "file": "motu-848-11-jpg.jpg",
  "bg": "bg/motu-848-11-jpg.jpg",
  "product": "p848",
  "w": 1149,
  "h": 1186,
  "ar": 0.969,
  "kind": "photo",
  "subject": "bundle",
  "alpha": false,
  "covers": [
   "MOTU 848 (11).jpg"
  ]
 },
 {
  "slug": "motu-848-11-png",
  "file": "motu-848-11-png.png",
  "bg": "bg/motu-848-11-png.jpg",
  "product": "p848",
  "w": 3000,
  "h": 466,
  "ar": 6.438,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 848 (11).png"
  ]
 },
 {
  "slug": "motu-848-12-png",
  "file": "motu-848-12-png.png",
  "bg": "bg/motu-848-12-png.jpg",
  "product": "p848",
  "w": 3000,
  "h": 504,
  "ar": 5.952,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 848 (12).png"
  ]
 },
 {
  "slug": "motu-848-13-jpg",
  "file": "motu-848-13-jpg.jpg",
  "bg": "bg/motu-848-13-jpg.jpg",
  "product": "p848",
  "w": 1353,
  "h": 941,
  "ar": 1.438,
  "kind": "photo",
  "subject": "mark",
  "alpha": false,
  "covers": [
   "MOTU 848 (13).jpg"
  ]
 },
 {
  "slug": "motu-848-15-jpg",
  "file": "motu-848-15-jpg.jpg",
  "bg": "bg/motu-848-15-jpg.jpg",
  "product": "p848",
  "w": 1000,
  "h": 611,
  "ar": 1.637,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 848 (15).jpg"
  ]
 },
 {
  "slug": "motu-848-16-jpg",
  "file": "motu-848-16-jpg.jpg",
  "bg": "bg/motu-848-16-jpg.jpg",
  "product": "p848",
  "w": 2000,
  "h": 1188,
  "ar": 1.684,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 848 (16).jpg"
  ]
 },
 {
  "slug": "motu-848-17-jpg",
  "file": "motu-848-17-jpg.jpg",
  "bg": "bg/motu-848-17-jpg.jpg",
  "product": "p848",
  "w": 3000,
  "h": 1780,
  "ar": 1.685,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 848 (17).jpg"
  ]
 },
 {
  "slug": "motu-848-18-jpg",
  "file": "motu-848-18-jpg.jpg",
  "bg": "bg/motu-848-18-jpg.jpg",
  "product": "p848",
  "w": 2000,
  "h": 1083,
  "ar": 1.847,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 848 (18).jpg"
  ]
 },
 {
  "slug": "motu-848-2-png",
  "file": "motu-848-2-png.png",
  "bg": "bg/motu-848-2-png.jpg",
  "product": "p848",
  "w": 1678,
  "h": 948,
  "ar": 1.77,
  "kind": "cutout",
  "subject": "bundle",
  "alpha": true,
  "covers": [
   "MOTU 848 (2).png"
  ]
 },
 {
  "slug": "motu-848-20-jpg",
  "file": "motu-848-20-jpg.jpg",
  "bg": "bg/motu-848-20-jpg.jpg",
  "product": "p848",
  "w": 1038,
  "h": 629,
  "ar": 1.65,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 848 (20).jpg"
  ]
 },
 {
  "slug": "motu-848-22-jpg",
  "file": "motu-848-22-jpg.jpg",
  "bg": "bg/motu-848-22-jpg.jpg",
  "product": "p848",
  "w": 1522,
  "h": 485,
  "ar": 3.138,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 848 (22).jpg"
  ]
 },
 {
  "slug": "motu-848-23-jpg",
  "file": "motu-848-23-jpg.jpg",
  "bg": "bg/motu-848-23-jpg.jpg",
  "product": "p848",
  "w": 1038,
  "h": 629,
  "ar": 1.65,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 848 (23).jpg"
  ]
 },
 {
  "slug": "motu-848-24-jpg",
  "file": "motu-848-24-jpg.jpg",
  "bg": "bg/motu-848-24-jpg.jpg",
  "product": "p848",
  "w": 3000,
  "h": 2008,
  "ar": 1.494,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 848 (24).jpg"
  ]
 },
 {
  "slug": "motu-848-25-jpg",
  "file": "motu-848-25-jpg.jpg",
  "bg": "bg/motu-848-25-jpg.jpg",
  "product": "p848",
  "w": 2000,
  "h": 714,
  "ar": 2.801,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 848 (25).jpg"
  ]
 },
 {
  "slug": "motu-848-26-jpg",
  "file": "motu-848-26-jpg.jpg",
  "bg": "bg/motu-848-26-jpg.jpg",
  "product": "p848",
  "w": 3000,
  "h": 1828,
  "ar": 1.641,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 848 (26).jpg"
  ]
 },
 {
  "slug": "motu-848-3-jpg",
  "file": "motu-848-3-jpg.jpg",
  "bg": "bg/motu-848-3-jpg.jpg",
  "product": "p848",
  "w": 2516,
  "h": 1415,
  "ar": 1.778,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 848 (3).jpg"
  ]
 },
 {
  "slug": "motu-848-3-png",
  "file": "motu-848-3-png.png",
  "bg": "bg/motu-848-3-png.jpg",
  "product": "p848",
  "w": 1652,
  "h": 1064,
  "ar": 1.553,
  "kind": "cutout",
  "subject": "mark",
  "alpha": true,
  "covers": [
   "MOTU 848 (3).png"
  ]
 },
 {
  "slug": "motu-848-4-jpg",
  "file": "motu-848-4-jpg.jpg",
  "bg": "bg/motu-848-4-jpg.jpg",
  "product": "p848",
  "w": 2000,
  "h": 1083,
  "ar": 1.847,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU 848 (4).jpg"
  ]
 },
 {
  "slug": "motu-848-5-jpg",
  "file": "motu-848-5-jpg.jpg",
  "bg": "bg/motu-848-5-jpg.jpg",
  "product": "p848",
  "w": 1149,
  "h": 1186,
  "ar": 0.969,
  "kind": "photo",
  "subject": "bundle",
  "alpha": false,
  "covers": [
   "MOTU 848 (5).jpg"
  ]
 },
 {
  "slug": "motu-848-6-png",
  "file": "motu-848-6-png.png",
  "bg": "bg/motu-848-6-png.jpg",
  "product": "p848",
  "w": 1691,
  "h": 290,
  "ar": 5.831,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 848 (6).png"
  ]
 },
 {
  "slug": "motu-848-7-png",
  "file": "motu-848-7-png.png",
  "bg": "bg/motu-848-7-png.jpg",
  "product": "p848",
  "w": 1761,
  "h": 773,
  "ar": 2.278,
  "kind": "cutout",
  "subject": "diagram",
  "alpha": true,
  "covers": [
   "MOTU 848 (7).png"
  ]
 },
 {
  "slug": "motu-848-8-png",
  "file": "motu-848-8-png.png",
  "bg": "bg/motu-848-8-png.jpg",
  "product": "p848",
  "w": 326,
  "h": 581,
  "ar": 0.561,
  "kind": "cutout",
  "subject": "diagram",
  "alpha": true,
  "covers": [
   "MOTU 848 (8).png"
  ]
 },
 {
  "slug": "motu-848-9-png",
  "file": "motu-848-9-png.png",
  "bg": "bg/motu-848-9-png.jpg",
  "product": "p848",
  "w": 950,
  "h": 783,
  "ar": 1.213,
  "kind": "cutout",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 848 (9).png"
  ]
 },
 {
  "slug": "motu-848-newly-added-1-jpg",
  "file": "motu-848-newly-added-1-jpg.jpg",
  "bg": "bg/motu-848-newly-added-1-jpg.jpg",
  "product": "p848",
  "w": 3000,
  "h": 1366,
  "ar": 2.196,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU 848 NEWLY ADDED (1).jpg"
  ]
 },
 {
  "slug": "motu-848-newly-added-1-png",
  "file": "motu-848-newly-added-1-png.png",
  "bg": "bg/motu-848-newly-added-1-png.jpg",
  "product": "p848",
  "w": 3000,
  "h": 744,
  "ar": 4.032,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 848 NEWLY ADDED (1).png"
  ]
 },
 {
  "slug": "motu-848-newly-added-2-png",
  "file": "motu-848-newly-added-2-png.png",
  "bg": "bg/motu-848-newly-added-2-png.jpg",
  "product": "p848",
  "w": 3000,
  "h": 716,
  "ar": 4.19,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 848 NEWLY ADDED (2).png"
  ]
 },
 {
  "slug": "motu-848-newly-added-3-png",
  "file": "motu-848-newly-added-3-png.png",
  "bg": "bg/motu-848-newly-added-3-png.jpg",
  "product": "p848",
  "w": 3000,
  "h": 771,
  "ar": 3.891,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 848 NEWLY ADDED (3).png"
  ]
 },
 {
  "slug": "motu-848-newly-added-4-png",
  "file": "motu-848-newly-added-4-png.png",
  "bg": "bg/motu-848-newly-added-4-png.jpg",
  "product": "p848",
  "w": 3000,
  "h": 735,
  "ar": 4.082,
  "kind": "strip",
  "subject": "hardware",
  "alpha": true,
  "covers": [
   "MOTU 848 NEWLY ADDED (4).png"
  ]
 },
 {
  "slug": "motu-16a-5-jpg",
  "file": "motu-16a-5-jpg.jpg",
  "bg": "bg/motu-16a-5-jpg.jpg",
  "product": "pswitch",
  "w": 3000,
  "h": 2414,
  "ar": 1.243,
  "kind": "photo",
  "subject": "diagram",
  "alpha": false,
  "covers": [
   "MOTU 16A (5).jpg",
   "MOTU 848 (8).jpg"
  ]
 },
 {
  "slug": "motu-avb-switch-1-jpg",
  "file": "motu-avb-switch-1-jpg.jpg",
  "bg": "bg/motu-avb-switch-1-jpg.jpg",
  "product": "pswitch",
  "w": 2370,
  "h": 1218,
  "ar": 1.946,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU AVB SWITCH (1).jpg"
  ]
 },
 {
  "slug": "motu-avb-switch-1-png",
  "file": "motu-avb-switch-1-png.png",
  "bg": "bg/motu-avb-switch-1-png.jpg",
  "product": "pswitch",
  "w": 960,
  "h": 640,
  "ar": 1.5,
  "kind": "cutout",
  "subject": "diagram",
  "alpha": true,
  "covers": [
   "MOTU AVB SWITCH (1).png"
  ]
 },
 {
  "slug": "motu-avb-switch-2-jpg",
  "file": "motu-avb-switch-2-jpg.jpg",
  "bg": "bg/motu-avb-switch-2-jpg.jpg",
  "product": "pswitch",
  "w": 2203,
  "h": 1238,
  "ar": 1.779,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU AVB SWITCH (2).jpg"
  ]
 },
 {
  "slug": "motu-avb-switch-3-jpg",
  "file": "motu-avb-switch-3-jpg.jpg",
  "bg": "bg/motu-avb-switch-3-jpg.jpg",
  "product": "pswitch",
  "w": 3000,
  "h": 1688,
  "ar": 1.777,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU AVB SWITCH (3).jpg"
  ]
 },
 {
  "slug": "motu-avb-switch-3-png",
  "file": "motu-avb-switch-3-png.png",
  "bg": "bg/motu-avb-switch-3-png.jpg",
  "product": "pswitch",
  "w": 1056,
  "h": 391,
  "ar": 2.701,
  "kind": "cutout",
  "subject": "context",
  "alpha": true,
  "covers": [
   "MOTU AVB SWITCH (3).png"
  ]
 },
 {
  "slug": "motu-avb-switch-4-jpg",
  "file": "motu-avb-switch-4-jpg.jpg",
  "bg": "bg/motu-avb-switch-4-jpg.jpg",
  "product": "pswitch",
  "w": 816,
  "h": 814,
  "ar": 1.002,
  "kind": "photo",
  "subject": "mark",
  "alpha": false,
  "covers": [
   "MOTU AVB SWITCH (4).jpg"
  ]
 },
 {
  "slug": "motu-avb-switch-5-png",
  "file": "motu-avb-switch-5-png.png",
  "bg": "bg/motu-avb-switch-5-png.jpg",
  "product": "pswitch",
  "w": 830,
  "h": 792,
  "ar": 1.048,
  "kind": "cutout",
  "subject": "mark",
  "alpha": true,
  "covers": [
   "MOTU AVB SWITCH (5).png"
  ]
 },
 {
  "slug": "motu-10pre-21-jpg",
  "file": "motu-10pre-21-jpg.jpg",
  "bg": "bg/motu-10pre-21-jpg.jpg",
  "product": "shared",
  "w": 2000,
  "h": 1052,
  "ar": 1.901,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 10pre (21).jpg",
   "MOTU 848 (21).jpg"
  ]
 },
 {
  "slug": "motu-10pre-22-jpg",
  "file": "motu-10pre-22-jpg.jpg",
  "bg": "bg/motu-10pre-22-jpg.jpg",
  "product": "shared",
  "w": 2000,
  "h": 1188,
  "ar": 1.684,
  "kind": "photo",
  "subject": "detail",
  "alpha": false,
  "covers": [
   "MOTU 10pre (22).jpg",
   "MOTU 848 (27).jpg"
  ]
 },
 {
  "slug": "motu-10pre-24-jpg",
  "file": "motu-10pre-24-jpg.jpg",
  "bg": "bg/motu-10pre-24-jpg.jpg",
  "product": "shared",
  "w": 1371,
  "h": 1001,
  "ar": 1.37,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 10pre (24).jpg",
   "MOTU 16A (4).jpg",
   "MOTU 848 (7).jpg"
  ]
 },
 {
  "slug": "motu-10pre-26-jpg",
  "file": "motu-10pre-26-jpg.jpg",
  "bg": "bg/motu-10pre-26-jpg.jpg",
  "product": "shared",
  "w": 1787,
  "h": 941,
  "ar": 1.899,
  "kind": "photo",
  "subject": "mark",
  "alpha": false,
  "covers": [
   "MOTU 10pre (26).jpg",
   "MOTU 16A (8).jpg",
   "MOTU 848 (9).jpg"
  ]
 },
 {
  "slug": "motu-10pre-27-jpg",
  "file": "motu-10pre-27-jpg.jpg",
  "bg": "bg/motu-10pre-27-jpg.jpg",
  "product": "shared",
  "w": 2070,
  "h": 994,
  "ar": 2.082,
  "kind": "photo",
  "subject": "ui",
  "alpha": false,
  "covers": [
   "MOTU 10pre (27).jpg",
   "MOTU 16A (20).jpg"
  ]
 },
 {
  "slug": "motu-10pre-28-jpg",
  "file": "motu-10pre-28-jpg.jpg",
  "bg": "bg/motu-10pre-28-jpg.jpg",
  "product": "shared",
  "w": 1353,
  "h": 941,
  "ar": 1.438,
  "kind": "photo",
  "subject": "mark",
  "alpha": false,
  "covers": [
   "MOTU 10pre (28).jpg",
   "MOTU 16A (22).jpg"
  ]
 },
 {
  "slug": "motu-16a-19-jpg",
  "file": "motu-16a-19-jpg.jpg",
  "bg": "bg/motu-16a-19-jpg.jpg",
  "product": "shared",
  "w": 2880,
  "h": 834,
  "ar": 3.453,
  "kind": "panel",
  "subject": "bundle",
  "alpha": false,
  "covers": [
   "MOTU 16A (19).jpg",
   "MOTU 848 (12).jpg"
  ]
 },
 {
  "slug": "motu-16a-2-png",
  "file": "motu-16a-2-png.png",
  "bg": "bg/motu-16a-2-png.jpg",
  "product": "shared",
  "w": 2562,
  "h": 1513,
  "ar": 1.693,
  "kind": "cutout",
  "subject": "ui",
  "alpha": true,
  "covers": [
   "MOTU 16A (2).png",
   "MOTU 848 (4).png"
  ]
 },
 {
  "slug": "motu-16a-23-jpg",
  "file": "motu-16a-23-jpg.jpg",
  "bg": "bg/motu-16a-23-jpg.jpg",
  "product": "shared",
  "w": 2000,
  "h": 1472,
  "ar": 1.359,
  "kind": "photo",
  "subject": "hardware",
  "alpha": false,
  "covers": [
   "MOTU 16A (23).jpg",
   "MOTU 848 (14).jpg"
  ]
 },
 {
  "slug": "motu-16a-3-png",
  "file": "motu-16a-3-png.png",
  "bg": "bg/motu-16a-3-png.jpg",
  "product": "shared",
  "w": 2880,
  "h": 1711,
  "ar": 1.683,
  "kind": "cutout",
  "subject": "ui",
  "alpha": true,
  "covers": [
   "MOTU 16A (3).png",
   "MOTU 848 (5).png"
  ]
 },
 {
  "slug": "motu-16a-8-png",
  "file": "motu-16a-8-png.png",
  "bg": "bg/motu-16a-8-png.jpg",
  "product": "shared",
  "w": 2204,
  "h": 644,
  "ar": 3.422,
  "kind": "strip",
  "subject": "detail",
  "alpha": true,
  "covers": [
   "MOTU 16A (8).png",
   "MOTU 848 (10).png"
  ]
 },
 {
  "slug": "motu-avb-switch-4-png",
  "file": "motu-avb-switch-4-png.png",
  "bg": "bg/motu-avb-switch-4-png.jpg",
  "product": "shared",
  "w": 581,
  "h": 836,
  "ar": 0.695,
  "kind": "cutout",
  "subject": "mark",
  "alpha": true,
  "covers": [
   "MOTU AVB SWITCH (4).png"
  ]
 }
];

export const REPO_FILE_COUNT = 139;
export const EXCLUDED_COUNT = 2;
