// AUTO-GENERATED by scripts/scan-higgsfield.mjs — do not edit by hand.
// Generated with Higgsfield (Nano Banana Pro stills from the real product
// photography as references; Kling 3.0 image-to-video B-roll from those stills).

export type HfStill = { id: string; file: string; bg: string; w: number; h: number; ar: number };
export type HfClip = { id: string; file: string; w: number; h: number; ar: number; seconds: number; fps: number };

export const HF_STILLS: HfStill[] = [
 {
  "id": "hero-rack",
  "file": "img-01-hero-rack.png",
  "bg": "bg/img-01-hero-rack.jpg",
  "w": 2752,
  "h": 1536,
  "ar": 1.792
 },
 {
  "id": "16a-mixroom",
  "file": "img-02-16a-mixroom.png",
  "bg": "bg/img-02-16a-mixroom.jpg",
  "w": 2752,
  "h": 1536,
  "ar": 1.792
 },
 {
  "id": "16a-modular",
  "file": "img-03-16a-modular.png",
  "bg": "bg/img-03-16a-modular.jpg",
  "w": 2752,
  "h": 1536,
  "ar": 1.792
 },
 {
  "id": "848-desk",
  "file": "img-04-848-desk.png",
  "bg": "bg/img-04-848-desk.jpg",
  "w": 2752,
  "h": 1536,
  "ar": 1.792
 },
 {
  "id": "848-podcast",
  "file": "img-05-848-podcast.png",
  "bg": "bg/img-05-848-podcast.jpg",
  "w": 2752,
  "h": 1536,
  "ar": 1.792
 },
 {
  "id": "848-atmos",
  "file": "img-06-848-atmos.png",
  "bg": "bg/img-06-848-atmos.jpg",
  "w": 2752,
  "h": 1536,
  "ar": 1.792
 },
 {
  "id": "10pre-tracking",
  "file": "img-07-10pre-tracking.png",
  "bg": "bg/img-07-10pre-tracking.jpg",
  "w": 2752,
  "h": 1536,
  "ar": 1.792
 },
 {
  "id": "10pre-stage",
  "file": "img-08-10pre-stage.png",
  "bg": "bg/img-08-10pre-stage.jpg",
  "w": 2752,
  "h": 1536,
  "ar": 1.792
 },
 {
  "id": "switch-foh",
  "file": "img-09-switch-foh.png",
  "bg": "bg/img-09-switch-foh.jpg",
  "w": 2752,
  "h": 1536,
  "ar": 1.792
 },
 {
  "id": "auditorium",
  "file": "img-10-auditorium.png",
  "bg": "bg/img-10-auditorium.jpg",
  "w": 2752,
  "h": 1536,
  "ar": 1.792
 },
 {
  "id": "hero-rack-9x16",
  "file": "img-21-hero-rack-9x16.png",
  "bg": "bg/img-21-hero-rack-9x16.jpg",
  "w": 1536,
  "h": 2752,
  "ar": 0.558
 },
 {
  "id": "16a-mixroom-9x16",
  "file": "img-22-16a-mixroom-9x16.png",
  "bg": "bg/img-22-16a-mixroom-9x16.jpg",
  "w": 1536,
  "h": 2752,
  "ar": 0.558
 },
 {
  "id": "848-desk-9x16",
  "file": "img-23-848-desk-9x16.png",
  "bg": "bg/img-23-848-desk-9x16.jpg",
  "w": 1536,
  "h": 2752,
  "ar": 0.558
 },
 {
  "id": "10pre-tracking-9x16",
  "file": "img-24-10pre-tracking-9x16.png",
  "bg": "bg/img-24-10pre-tracking-9x16.jpg",
  "w": 1536,
  "h": 2752,
  "ar": 0.558
 },
 {
  "id": "switch-foh-9x16",
  "file": "img-26-switch-foh-9x16.png",
  "bg": "bg/img-26-switch-foh-9x16.jpg",
  "w": 1536,
  "h": 2752,
  "ar": 0.558
 }
];
export const HF_CLIPS: HfClip[] = [
 {
  "id": "hero-rack",
  "file": "clip-31-hero-rack.mp4",
  "w": 1928,
  "h": 1076,
  "ar": 1.792,
  "seconds": 5.04,
  "fps": 24
 },
 {
  "id": "16a-mixroom",
  "file": "clip-32-16a-mixroom.mp4",
  "w": 1928,
  "h": 1076,
  "ar": 1.792,
  "seconds": 5.04,
  "fps": 24
 },
 {
  "id": "848-desk",
  "file": "clip-33-848-desk.mp4",
  "w": 1928,
  "h": 1076,
  "ar": 1.792,
  "seconds": 5.04,
  "fps": 24
 },
 {
  "id": "switch-foh",
  "file": "clip-34-switch-foh.mp4",
  "w": 1928,
  "h": 1076,
  "ar": 1.792,
  "seconds": 5.04,
  "fps": 24
 },
 {
  "id": "16a-modular",
  "file": "clip-35-16a-modular.mp4",
  "w": 1928,
  "h": 1076,
  "ar": 1.792,
  "seconds": 5.04,
  "fps": 24
 }
];

/** A still by id; portrait variants carry the same id with a "-9x16" suffix. */
export const still = (id: string): HfStill | undefined => HF_STILLS.find((s) => s.id === id);
export const clip = (id: string): HfClip | undefined => HF_CLIPS.find((c) => c.id === id);
