// Builds ASSET_COVERAGE.md by parsing the actual scene source, so the ledger
// can never drift from what the reels really show.
//
// Tiers:
//   HERO    — ProductPlate / ContrastBand / thumbnail hero (its own moment)
//   RUN     — ImageRun (cross-faded single-image stage, a real beat each)
//   MONTAGE — Montage grid cell (efficient coverage tier)
//   AMBIENT — Scene ambientImage: blurred top/bottom-zone fill (Section 2b)
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const map = JSON.parse(fs.readFileSync(path.join(ROOT, "public", "images", "_map.json"), "utf8"));
const schedule = JSON.parse(fs.readFileSync(path.join(ROOT, "src", "schedule.json"), "utf8"));

const EXCLUDED = {
  "MOTU 10pre (23).jpg": "Moog modular synthesizer — third-party hardware, not any MOTU product",
  "MOTU 16A (3).jpg": "byte-identical to MOTU 10pre (23).jpg — same Moog photograph",
  "MOTU 848 (6).jpg": "byte-identical to MOTU 10pre (23).jpg — same Moog photograph",
};

const slugToOrig = Object.fromEntries(Object.entries(map).map(([o, s]) => [s, o]));

// duplicate groups, by slug
const bySize = {};
for (const [orig, slug] of Object.entries(map)) {
  const p = path.join(ROOT, "public", "images", slug);
  const h = fs.statSync(p).size + ":" + fs.readFileSync(p).subarray(0, 4096).toString("base64").slice(0, 64);
  (bySize[h] ||= []).push(slug);
}
const dupOf = {};
for (const group of Object.values(bySize)) {
  if (group.length > 1) {
    const [first, ...rest] = group.sort();
    for (const r of rest) dupOf[r] = first;
  }
}

const usage = {}; // slug -> [{part, scene, tier}]
const record = (slug, part, scene, tier) => {
  (usage[slug] ||= []).push({ part, scene, tier });
};

for (const partKey of Object.keys(schedule.parts)) {
  const file = path.join(ROOT, "src", "scenes", `part${partKey}.tsx`);
  if (!fs.existsSync(file)) continue;
  const src = fs.readFileSync(file, "utf8");

  // split source per exported scene component
  const chunks = src.split(/export const (S\d+_\w+)/).slice(1);
  for (let i = 0; i < chunks.length; i += 2) {
    const scene = chunks[i];
    const body = chunks[i + 1];

    for (const m of body.matchAll(/ambientImage="([^"]+)"/g)) record(m[1], partKey, scene, "AMBIENT");
    for (const m of body.matchAll(/<ProductPlate\s+src="([^"]+)"/g)) record(m[1], partKey, scene, "HERO");
    for (const m of body.matchAll(/<ContrastBand\s+src="([^"]+)"/g)) record(m[1], partKey, scene, "HERO");
    for (const m of body.matchAll(/<ImageRun[\s\S]*?images=\{\[([\s\S]*?)\]\}/g))
      for (const s of m[1].matchAll(/"([^"]+)"/g)) record(s[1], partKey, scene, "RUN");
    for (const m of body.matchAll(/<Montage[\s\S]*?images=\{\[([\s\S]*?)\]\}/g))
      for (const s of m[1].matchAll(/"([^"]+)"/g)) record(s[1], partKey, scene, "MONTAGE");
  }
}

// thumbnails
const thumbSrc = fs.readFileSync(path.join(ROOT, "src", "Thumbnails.tsx"), "utf8");
for (const m of thumbSrc.matchAll(/hero="([^"]+)"/g)) record(m[1], "T", "Thumbnail", "HERO");
for (const m of thumbSrc.matchAll(/heroSecondary="([^"]+)"/g)) record(m[1], "T", "Thumbnail", "HERO");

const all = Object.values(map).sort((a, b) => a.localeCompare(b, "en", { numeric: true }));
const covered = all.filter((s) => usage[s]);
const uncovered = all.filter((s) => !usage[s]);

const rank = { HERO: 3, RUN: 2, MONTAGE: 1, AMBIENT: 0 };
const bestTier = (s) => (usage[s] || []).sort((a, b) => rank[b.tier] - rank[a.tier])[0]?.tier ?? "—";

const group = (prefixes) =>
  all.filter((s) => prefixes.some((p) => slugToOrig[s].startsWith(p)));

const G = {
  "MOTU 10pre": group(["MOTU 10pre", "MOTU 10PRE"]),
  "MOTU 16A": group(["MOTU 16A"]),
  "MOTU 848": group(["MOTU 848"]),
  "MOTU AVB Switch": group(["MOTU AVB SWITCH"]),
};

let md = `# ASSET COVERAGE LEDGER — MOTU AVB Series three-part reel series

Auto-generated by \`scripts/coverage.mjs\` from the actual scene source.
Cumulative across Parts 1–3 (never reset per part).

## Headline

| | |
|---|---|
| Files in repo (product/context imagery) | **139** |
| Confirmed content-mismatch exclusions | **3** |
| **Valid images requiring coverage** | **136** |
| Covered so far | **${covered.length}** |
| Remaining | **${uncovered.length}** |

## Confirmed exclusions (content verified, not filename-trusted)

| File | Why excluded |
|---|---|
${Object.entries(EXCLUDED).map(([f, r]) => `| \`${f}\` | ${r} |`).join("\n")}

All three are byte-identical to one another: a single photograph of a Moog
modular synthesizer saved under three different MOTU product filenames. It shows
no MOTU hardware and no MOTU-related software or context, so it is excluded from
the series entirely rather than silently re-captioned.

## Coverage by product

| Product | Valid | Covered | Remaining |
|---|---|---|---|
${Object.entries(G)
  .map(([k, v]) => `| ${k} | ${v.length} | ${v.filter((s) => usage[s]).length} | ${v.filter((s) => !usage[s]).length} |`)
  .join("\n")}

## Tier definitions

| Tier | Meaning |
|---|---|
| **HERO** | Its own framed moment — \`ProductPlate\` / \`ContrastBand\` / thumbnail hero |
| **RUN** | \`ImageRun\` cross-faded stage — a real individual beat, briefer than hero |
| **MONTAGE** | Grid cell — efficient coverage tier for context/secondary material |
| **AMBIENT** | Blurred top/bottom non-critical-zone fill (Section 2b) |

## Full ledger

| # | File (original name) | Best tier | Part · Scene(s) | Note |
|---|---|---|---|---|
`;

all.forEach((s, i) => {
  const u = usage[s] || [];
  const where = u.length
    ? [...new Set(u.map((x) => `P${x.part}·${x.scene.split("_")[0]}`))].join(", ")
    : "—";
  const note = dupOf[s] ? `byte-identical to \`${slugToOrig[dupOf[s]]}\`` : "";
  md += `| ${i + 1} | \`${slugToOrig[s]}\` | ${bestTier(s)} | ${where} | ${note} |\n`;
});

if (uncovered.length) {
  md += `\n## Not yet covered (${uncovered.length})\n\n`;
  md += uncovered.map((s) => `- \`${slugToOrig[s]}\``).join("\n") + "\n";
}

fs.writeFileSync(path.join(ROOT, "ASSET_COVERAGE.md"), md);
console.log(`valid ${all.length} | covered ${covered.length} | remaining ${uncovered.length}`);
for (const [k, v] of Object.entries(G)) {
  console.log(`  ${k.padEnd(18)} ${v.filter((s) => usage[s]).length}/${v.length}`);
}
if (uncovered.length) {
  console.log("\nremaining:");
  for (const s of uncovered) console.log("   " + slugToOrig[s]);
}
