// Generate src/assets.ts from the copied-image map so every reference in a
// scene is guaranteed to resolve to a real file on disk.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const map = JSON.parse(fs.readFileSync(path.resolve(ROOT, "public", "images", "_map.json"), "utf8"));

const bucket = (prefixes) =>
  Object.entries(map)
    .filter(([orig]) => prefixes.some((p) => orig.startsWith(p)))
    .map(([, slug]) => slug)
    .sort((a, b) => a.localeCompare(b, "en", { numeric: true }));

const TENPRE = bucket(["MOTU 10pre", "MOTU 10PRE"]);
const SIXTEENA = bucket(["MOTU 16A"]);
const EIGHT48 = bucket(["MOTU 848"]);
const AVBSW = bucket(["MOTU AVB SWITCH"]);

const lit = (arr) => `[\n${arr.map((s) => `  ${JSON.stringify(s)},`).join("\n")}\n]`;

const out = `// AUTO-GENERATED by scripts/gen-assets.mjs — do not edit by hand.
// Every entry is a file that exists in public/images/.
// Content-mismatched files are excluded upstream in scripts/copy-assets.mjs.

export const TENPRE_ALL = ${lit(TENPRE)} as const;
export const SIXTEENA_ALL = ${lit(SIXTEENA)} as const;
export const EIGHT48_ALL = ${lit(EIGHT48)} as const;
export const AVBSW_ALL = ${lit(AVBSW)} as const;

export const ALL_IMAGES: readonly string[] = [
  ...TENPRE_ALL, ...SIXTEENA_ALL, ...EIGHT48_ALL, ...AVBSW_ALL,
];

export const img = (slug: string) => \`images/\${slug}\`;
`;

fs.writeFileSync(path.resolve(ROOT, "src", "assets.ts"), out);
console.log(
  `assets.ts written — 10pre:${TENPRE.length} 16A:${SIXTEENA.length} 848:${EIGHT48.length} avb:${AVBSW.length} total:${
    TENPRE.length + SIXTEENA.length + EIGHT48.length + AVBSW.length
  }`
);
