// AUTO-GENERATED by sync-assets.mjs - do not edit by hand.
// Content classifications are derived from visual inspection of every image,
// NOT from filenames (filenames do not reliably identify the product depicted).
export type AssetClass = 'hero' | 'macro' | 'panel' | 'software' | 'diagram' | 'logo' | 'context';

export type Asset = {
  idx: number;
  /** original repo filename */
  src: string;
  /** slug under public/img/ */
  slug: string;
  desc: string;
  cls: AssetClass;
  /** product actually depicted, or 'shared' */
  prod: '10pre' | '16A' | '848' | 'shared';
  part: 1 | 2 | 3;
};

export const ASSETS: Asset[] = [
 {
  "idx": 0,
  "src": "MOTU 10pre (1).jpg",
  "slug": "10pre-01.jpg",
  "desc": "Mic snake cabling into 10pre rear panel (black bg)",
  "cls": "context",
  "prod": "10pre",
  "part": 1
 },
 {
  "idx": 1,
  "src": "MOTU 10pre (1).png",
  "slug": "10pre-01p.png",
  "desc": "CueMix Pro routing/grid matrix window",
  "cls": "software",
  "prod": "10pre",
  "part": 1
 },
 {
  "idx": 2,
  "src": "MOTU 10pre (2).jpg",
  "slug": "10pre-02.jpg",
  "desc": "Rear macro: NETWORK + OPTICAL + Thunderbolt + LINE OUT 3-8",
  "cls": "macro",
  "prod": "10pre",
  "part": 1
 },
 {
  "idx": 3,
  "src": "MOTU 10pre (3).jpg",
  "slug": "10pre-03.jpg",
  "desc": "CueMix Pro channel strip - GATE + COMPRESSOR",
  "cls": "software",
  "prod": "10pre",
  "part": 1
 },
 {
  "idx": 4,
  "src": "MOTU 10pre (4).jpg",
  "slug": "10pre-04.jpg",
  "desc": "CueMix Pro 4-band parametric EQ curve",
  "cls": "software",
  "prod": "10pre",
  "part": 1
 },
 {
  "idx": 5,
  "src": "MOTU 10pre (4).png",
  "slug": "10pre-04p.png",
  "desc": "10pre FRONT PANEL hero, light bg",
  "cls": "hero",
  "prod": "10pre",
  "part": 1
 },
 {
  "idx": 6,
  "src": "MOTU 10pre (5).jpg",
  "slug": "10pre-05.jpg",
  "desc": "CueMix Pro Discovery - 10pre/848/16A on network",
  "cls": "software",
  "prod": "shared",
  "part": 1
 },
 {
  "idx": 7,
  "src": "MOTU 10pre (6).jpg",
  "slug": "10pre-06.jpg",
  "desc": "CueMix Pro outputs: monitor, phones 1+2, presets, talkback",
  "cls": "software",
  "prod": "10pre",
  "part": 1
 },
 {
  "idx": 8,
  "src": "MOTU 10pre (7).jpg",
  "slug": "10pre-07.jpg",
  "desc": "CueMix Pro MIC INPUTS 1-10 (ten preamps, 48V/PAD)",
  "cls": "software",
  "prod": "10pre",
  "part": 1
 },
 {
  "idx": 9,
  "src": "MOTU 10pre (8).jpg",
  "slug": "10pre-08.jpg",
  "desc": "CueMix Pro mix settings / fader bank",
  "cls": "software",
  "prod": "10pre",
  "part": 1
 },
 {
  "idx": 10,
  "src": "MOTU 10pre (8).png",
  "slug": "10pre-08p.png",
  "desc": "10pre REAR PANEL full array, light bg",
  "cls": "hero",
  "prod": "10pre",
  "part": 1
 },
 {
  "idx": 11,
  "src": "MOTU 10pre (9).jpg",
  "slug": "10pre-09.jpg",
  "desc": "CueMix Pro outputs page - monitor/phones/line outs",
  "cls": "software",
  "prod": "10pre",
  "part": 1
 },
 {
  "idx": 12,
  "src": "MOTU 10pre (10).jpg",
  "slug": "10pre-10.jpg",
  "desc": "CueMix Pro PATCHBAY sources->destinations",
  "cls": "software",
  "prod": "10pre",
  "part": 1
 },
 {
  "idx": 13,
  "src": "MOTU 10pre (10).png",
  "slug": "10pre-10p.png",
  "desc": "10pre front-panel labelled line diagram",
  "cls": "diagram",
  "prod": "10pre",
  "part": 1
 },
 {
  "idx": 14,
  "src": "MOTU 10pre (11).jpg",
  "slug": "10pre-11.jpg",
  "desc": "MACRO: 2 front combo XLR + INSERTS SND/RET ch1-2",
  "cls": "macro",
  "prod": "10pre",
  "part": 1
 },
 {
  "idx": 15,
  "src": "MOTU 10pre (11).png",
  "slug": "10pre-11p.png",
  "desc": "10pre full system connection diagram",
  "cls": "diagram",
  "prod": "10pre",
  "part": 1
 },
 {
  "idx": 16,
  "src": "MOTU 10pre (12).jpg",
  "slug": "10pre-12.jpg",
  "desc": "10pre TFT display macro - PHONES/IN/OUT/MONITOR",
  "cls": "macro",
  "prod": "10pre",
  "part": 1
 },
 {
  "idx": 17,
  "src": "MOTU 10pre (12).png",
  "slug": "10pre-12p.png",
  "desc": "Round-trip latency diagram ~1.8ms",
  "cls": "diagram",
  "prod": "shared",
  "part": 1
 },
 {
  "idx": 18,
  "src": "MOTU 10pre (13).jpg",
  "slug": "10pre-13.jpg",
  "desc": "MACRO: rear combo XLR MIC/LINE/INSTRUMENT IN ch3-6",
  "cls": "macro",
  "prod": "10pre",
  "part": 1
 },
 {
  "idx": 19,
  "src": "MOTU 10pre (13).png",
  "slug": "10pre-13p.png",
  "desc": "MOTU 40Gbps 240W Thunderbolt cable",
  "cls": "context",
  "prod": "shared",
  "part": 1
 },
 {
  "idx": 20,
  "src": "MOTU 10pre (14).jpg",
  "slug": "10pre-14.jpg",
  "desc": "CueMix Pro on desktop display",
  "cls": "software",
  "prod": "10pre",
  "part": 1
 },
 {
  "idx": 21,
  "src": "MOTU 10pre (14).png",
  "slug": "10pre-14p.png",
  "desc": "CueMix Pro for iOS on iPad above 10pre",
  "cls": "software",
  "prod": "10pre",
  "part": 1
 },
 {
  "idx": 22,
  "src": "MOTU 10pre (15).jpg",
  "slug": "10pre-15.jpg",
  "desc": "MONITOR GROUP button row 1-8 macro",
  "cls": "macro",
  "prod": "10pre",
  "part": 1
 },
 {
  "idx": 23,
  "src": "MOTU 10pre (16).jpg",
  "slug": "10pre-16.jpg",
  "desc": "Studio control room context (desk, monitors, console)",
  "cls": "context",
  "prod": "shared",
  "part": 1
 },
 {
  "idx": 24,
  "src": "MOTU 10pre (17).jpg",
  "slug": "10pre-17.jpg",
  "desc": "10pre TFT display macro, angled",
  "cls": "macro",
  "prod": "10pre",
  "part": 1
 },
 {
  "idx": 25,
  "src": "MOTU 10pre (18).jpg",
  "slug": "10pre-18.jpg",
  "desc": "MACRO: LINE OUT 1-8 TRS jacks",
  "cls": "macro",
  "prod": "10pre",
  "part": 1
 },
 {
  "idx": 26,
  "src": "MOTU 10pre (19).jpg",
  "slug": "10pre-19.jpg",
  "desc": "10pre full front panel on black",
  "cls": "hero",
  "prod": "10pre",
  "part": 1
 },
 {
  "idx": 36,
  "src": "MOTU 10pre (29).jpg",
  "slug": "10pre-29.jpg",
  "desc": "MACRO: dual headphone outputs 1+2 with level knobs",
  "cls": "macro",
  "prod": "10pre",
  "part": 1
 },
 {
  "idx": 31,
  "src": "MOTU 10pre (24).jpg",
  "slug": "10pre-24.jpg",
  "desc": "CueMix Pro on iPad, angled (shared asset x3)",
  "cls": "software",
  "prod": "shared",
  "part": 1
 },
 {
  "idx": 33,
  "src": "MOTU 10pre (26).jpg",
  "slug": "10pre-26.jpg",
  "desc": "ESS Technology logo",
  "cls": "logo",
  "prod": "shared",
  "part": 1
 },
 {
  "idx": 35,
  "src": "MOTU 10pre (28).jpg",
  "slug": "10pre-28.jpg",
  "desc": "Thunderbolt logo",
  "cls": "logo",
  "prod": "shared",
  "part": 1
 },
 {
  "idx": 30,
  "src": "MOTU 10pre (23).jpg",
  "slug": "10pre-23.jpg",
  "desc": "Moog modular synthesizer (DC-coupled CV use case)",
  "cls": "context",
  "prod": "shared",
  "part": 2
 },
 {
  "idx": 34,
  "src": "MOTU 10pre (27).jpg",
  "slug": "10pre-27.jpg",
  "desc": "CueMix Pro Reverb plug-in UI",
  "cls": "software",
  "prod": "shared",
  "part": 2
 },
 {
  "idx": 37,
  "src": "MOTU 16A (1).jpg",
  "slug": "16a-01.jpg",
  "desc": "16A on desk, dual displays lit, mic in frame",
  "cls": "hero",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 38,
  "src": "MOTU 16A (1).png",
  "slug": "16a-01p.png",
  "desc": "CueMix Pro application icon",
  "cls": "logo",
  "prod": "shared",
  "part": 2
 },
 {
  "idx": 39,
  "src": "MOTU 16A (2).jpg",
  "slug": "16a-02.jpg",
  "desc": "16A TFT display macro PHONES/INPUTS/OUTPUTS/MONITOR",
  "cls": "macro",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 40,
  "src": "MOTU 16A (2).png",
  "slug": "16a-02p.png",
  "desc": "DAW session - clip/scene grid",
  "cls": "software",
  "prod": "shared",
  "part": 2
 },
 {
  "idx": 41,
  "src": "MOTU 16A (3).png",
  "slug": "16a-03p.png",
  "desc": "DAW session - arrangement timeline",
  "cls": "software",
  "prod": "shared",
  "part": 2
 },
 {
  "idx": 42,
  "src": "MOTU 16A (4).jpg",
  "slug": "16a-04.jpg",
  "desc": "16A front-panel labelled line diagram",
  "cls": "diagram",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 43,
  "src": "MOTU 16A (5).jpg",
  "slug": "16a-05.jpg",
  "desc": "AVB topology diagram - 16A daisy-chain + AVB switch",
  "cls": "diagram",
  "prod": "shared",
  "part": 2
 },
 {
  "idx": 44,
  "src": "MOTU 16A (5).png",
  "slug": "16a-05p.png",
  "desc": "16A full system connection diagram",
  "cls": "diagram",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 45,
  "src": "MOTU 16A (6).jpg",
  "slug": "16a-06.jpg",
  "desc": "CueMix Discovery - 16A, 16A#2, 16A#3, 16A#4 stacked",
  "cls": "software",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 46,
  "src": "MOTU 16A (6).png",
  "slug": "16a-06p.png",
  "desc": "Round-trip latency diagram 16A ~1.8ms",
  "cls": "diagram",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 47,
  "src": "MOTU 16A (7).jpg",
  "slug": "16a-07.jpg",
  "desc": "CueMix channel strip Line In 5 - gate + compressor",
  "cls": "software",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 48,
  "src": "MOTU 16A (7).png",
  "slug": "16a-07p.png",
  "desc": "CueMix Pro for iOS with 16A",
  "cls": "software",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 49,
  "src": "MOTU 16A (8).jpg",
  "slug": "16a-08.jpg",
  "desc": "Rear macro: WORD CLOCK BNC + NETWORK + OPTICAL + TB",
  "cls": "macro",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 50,
  "src": "MOTU 16A (9).jpg",
  "slug": "16a-09.jpg",
  "desc": "CueMix HOME - monitor, headphones, monitor group, talkback",
  "cls": "software",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 51,
  "src": "MOTU 16A (9).png",
  "slug": "16a-09p.png",
  "desc": "16A FRONT PANEL hero - DUAL TFT displays, light bg",
  "cls": "hero",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 52,
  "src": "MOTU 16A (10).jpg",
  "slug": "16a-10.jpg",
  "desc": "CueMix INPUT TRIM - Line In 1-16",
  "cls": "software",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 53,
  "src": "MOTU 16A (10).png",
  "slug": "16a-10p.png",
  "desc": "16A front panel wide strip (dual displays)",
  "cls": "hero",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 54,
  "src": "MOTU 16A (11).jpg",
  "slug": "16a-11.jpg",
  "desc": "CueMix channel strip MIX SENDS - aux buses",
  "cls": "software",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 55,
  "src": "MOTU 16A (11).png",
  "slug": "16a-11p.png",
  "desc": "16A front panel wide strip variant",
  "cls": "hero",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 56,
  "src": "MOTU 16A (12).jpg",
  "slug": "16a-12.jpg",
  "desc": "CueMix Pro on desktop display",
  "cls": "software",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 57,
  "src": "MOTU 16A (12).png",
  "slug": "16a-12p.png",
  "desc": "16A front panel wide strip variant",
  "cls": "hero",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 58,
  "src": "MOTU 16A (13).jpg",
  "slug": "16a-13.jpg",
  "desc": "CueMix mix settings / fader bank 16A",
  "cls": "software",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 59,
  "src": "MOTU 16A (13).png",
  "slug": "16a-13p.png",
  "desc": "16A REAR PANEL - 16 LINE OUT + 16 LINE IN, light bg",
  "cls": "hero",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 60,
  "src": "MOTU 16A (14).jpg",
  "slug": "16a-14.jpg",
  "desc": "CueMix OUTPUT TRIM - Line Out 1-16",
  "cls": "software",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 61,
  "src": "MOTU 16A (15).jpg",
  "slug": "16a-15.jpg",
  "desc": "CueMix 4-band parametric EQ 16A",
  "cls": "software",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 62,
  "src": "MOTU 16A (16).jpg",
  "slug": "16a-16.jpg",
  "desc": "CueMix PATCH BAY - Line Inputs 1-16 routed to destinations",
  "cls": "software",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 63,
  "src": "MOTU 16A (17).jpg",
  "slug": "16a-17.jpg",
  "desc": "CueMix PATCH BAY variant - line inputs to host",
  "cls": "software",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 64,
  "src": "MOTU 16A (18).jpg",
  "slug": "16a-18.jpg",
  "desc": "16A with laptop on top, displays glowing (hero/lifestyle)",
  "cls": "hero",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 65,
  "src": "MOTU 16A (19).jpg",
  "slug": "16a-19.jpg",
  "desc": "DAW plug-in collage (bundled software)",
  "cls": "software",
  "prod": "shared",
  "part": 2
 },
 {
  "idx": 66,
  "src": "MOTU 16A (21).jpg",
  "slug": "16a-21.jpg",
  "desc": "MACRO: rear OPTICAL + LINE OUT dense TRS rows",
  "cls": "macro",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 67,
  "src": "MOTU 16A (23).jpg",
  "slug": "16a-23.jpg",
  "desc": "MOTU 40Gbps Thunderbolt cable",
  "cls": "context",
  "prod": "shared",
  "part": 2
 },
 {
  "idx": 68,
  "src": "MOTU 16A (24).jpg",
  "slug": "16a-24.jpg",
  "desc": "MACRO: LINE OUT TRS jacks 5-14",
  "cls": "macro",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 69,
  "src": "MOTU 16A (25).jpg",
  "slug": "16a-25.jpg",
  "desc": "16A rear fully patched, top-down with cable fan",
  "cls": "context",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 70,
  "src": "MOTU 16A (26).jpg",
  "slug": "16a-26.jpg",
  "desc": "CueMix routing matrix grid",
  "cls": "software",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 71,
  "src": "MOTU 16A (28).jpg",
  "slug": "16a-28.jpg",
  "desc": "MACRO: NETWORK RJ45 + OPTICAL + Thunderbolt",
  "cls": "macro",
  "prod": "16A",
  "part": 2
 },
 {
  "idx": 27,
  "src": "MOTU 10pre (20).jpg",
  "slug": "10pre-20.jpg",
  "desc": "MACRO: A / B / C + MUTE / MONO / TALK monitor buttons",
  "cls": "macro",
  "prod": "848",
  "part": 3
 },
 {
  "idx": 28,
  "src": "MOTU 10pre (21).jpg",
  "slug": "10pre-21.jpg",
  "desc": "CueMix PATCHBAY - Proxy Device: 848 host outputs",
  "cls": "software",
  "prod": "848",
  "part": 3
 },
 {
  "idx": 29,
  "src": "MOTU 10pre (22).jpg",
  "slug": "10pre-22.jpg",
  "desc": "MACRO: NETWORK + OPTICAL + Thunderbolt rear cluster",
  "cls": "macro",
  "prod": "848",
  "part": 3
 },
 {
  "idx": 32,
  "src": "MOTU 10pre (25).jpg",
  "slug": "10pre-25.jpg",
  "desc": "AVB topology - 10pre/848/16A daisy-chain + AVB switch",
  "cls": "diagram",
  "prod": "shared",
  "part": 3
 },
 {
  "idx": 72,
  "src": "MOTU 848 (1).jpg",
  "slug": "848-01.jpg",
  "desc": "Studio control room with monitor array + console",
  "cls": "context",
  "prod": "shared",
  "part": 3
 },
 {
  "idx": 73,
  "src": "MOTU 848 (1).png",
  "slug": "848-01p.png",
  "desc": "CueMix Pro application icon",
  "cls": "logo",
  "prod": "shared",
  "part": 3
 },
 {
  "idx": 74,
  "src": "MOTU 848 (2).jpg",
  "slug": "848-02.jpg",
  "desc": "848 full front panel on black",
  "cls": "hero",
  "prod": "848",
  "part": 3
 },
 {
  "idx": 75,
  "src": "MOTU 848 (2).png",
  "slug": "848-02p.png",
  "desc": "MOTU Instruments soundbank collage",
  "cls": "context",
  "prod": "shared",
  "part": 3
 },
 {
  "idx": 76,
  "src": "MOTU 848 (3).jpg",
  "slug": "848-03.jpg",
  "desc": "CueMix routing matrix grid 848",
  "cls": "software",
  "prod": "848",
  "part": 3
 },
 {
  "idx": 77,
  "src": "MOTU 848 (3).png",
  "slug": "848-03p.png",
  "desc": "Milan (Avnu) certification logo",
  "cls": "logo",
  "prod": "shared",
  "part": 3
 },
 {
  "idx": 78,
  "src": "MOTU 848 (4).jpg",
  "slug": "848-04.jpg",
  "desc": "848 TFT display macro PHONES/IN/OUT/MONITOR",
  "cls": "macro",
  "prod": "848",
  "part": 3
 },
 {
  "idx": 79,
  "src": "MOTU 848 (5).png",
  "slug": "848-05p.png",
  "desc": "Big Fish Audio content-bundle logo",
  "cls": "logo",
  "prod": "shared",
  "part": 3
 },
 {
  "idx": 80,
  "src": "MOTU 848 (6).jpg",
  "slug": "848-06.jpg",
  "desc": "848 front-panel labelled line diagram",
  "cls": "diagram",
  "prod": "848",
  "part": 3
 },
 {
  "idx": 81,
  "src": "MOTU 848 (7).jpg",
  "slug": "848-07.jpg",
  "desc": "848 full system connection diagram",
  "cls": "diagram",
  "prod": "848",
  "part": 3
 },
 {
  "idx": 82,
  "src": "MOTU 848 (8).jpg",
  "slug": "848-08.jpg",
  "desc": "Round-trip latency diagram 848 ~1.8ms",
  "cls": "diagram",
  "prod": "848",
  "part": 3
 },
 {
  "idx": 83,
  "src": "MOTU 848 (9).jpg",
  "slug": "848-09.jpg",
  "desc": "CueMix Pro for iOS with 848 (gain knobs, combos)",
  "cls": "software",
  "prod": "848",
  "part": 3
 },
 {
  "idx": 84,
  "src": "MOTU 848 (10).jpg",
  "slug": "848-10.jpg",
  "desc": "Loopmasters content-bundle logo",
  "cls": "logo",
  "prod": "shared",
  "part": 3
 },
 {
  "idx": 85,
  "src": "MOTU 848 (11).jpg",
  "slug": "848-11.jpg",
  "desc": "Lucid Samples content-bundle logo",
  "cls": "logo",
  "prod": "shared",
  "part": 3
 },
 {
  "idx": 86,
  "src": "MOTU 848 (11).png",
  "slug": "848-11p.png",
  "desc": "848 FRONT PANEL hero, light bg",
  "cls": "hero",
  "prod": "848",
  "part": 3
 },
 {
  "idx": 87,
  "src": "MOTU 848 (12).jpg",
  "slug": "848-12.jpg",
  "desc": "848 REAR PANEL full array, light bg",
  "cls": "hero",
  "prod": "848",
  "part": 3
 },
 {
  "idx": 88,
  "src": "MOTU 848 (13).jpg",
  "slug": "848-13.jpg",
  "desc": "Thunderbolt logo",
  "cls": "logo",
  "prod": "shared",
  "part": 3
 },
 {
  "idx": 89,
  "src": "MOTU 848 (15).jpg",
  "slug": "848-15.jpg",
  "desc": "MACRO: dual headphone outputs 1+2 with knobs",
  "cls": "macro",
  "prod": "848",
  "part": 3
 },
 {
  "idx": 90,
  "src": "MOTU 848 (16).jpg",
  "slug": "848-16.jpg",
  "desc": "MACRO: LINE OUT TRS jacks 3-12 (Atmos array)",
  "cls": "macro",
  "prod": "848",
  "part": 3
 },
 {
  "idx": 91,
  "src": "MOTU 848 (17).jpg",
  "slug": "848-17.jpg",
  "desc": "Cable snake into 848 rear panel (black bg)",
  "cls": "context",
  "prod": "848",
  "part": 3
 },
 {
  "idx": 92,
  "src": "MOTU 848 (18).jpg",
  "slug": "848-18.jpg",
  "desc": "MACRO: NETWORK + OPTICAL + LINE OUT 7-12",
  "cls": "macro",
  "prod": "848",
  "part": 3
 },
 {
  "idx": 93,
  "src": "MOTU 848 (20).jpg",
  "slug": "848-20.jpg",
  "desc": "MACRO: INSERTS SND/RET ch3-4 + MIC/LINE/INST combos",
  "cls": "macro",
  "prod": "848",
  "part": 3
 },
 {
  "idx": 94,
  "src": "MOTU 848 (22).jpg",
  "slug": "848-22.jpg",
  "desc": "848 TFT display macro, wide",
  "cls": "macro",
  "prod": "848",
  "part": 3
 },
 {
  "idx": 95,
  "src": "MOTU 848 (23).jpg",
  "slug": "848-23.jpg",
  "desc": "MACRO: MIC/LINE/INSTRUMENT IN combos 1-4",
  "cls": "macro",
  "prod": "848",
  "part": 3
 },
 {
  "idx": 96,
  "src": "MOTU 848 (24).jpg",
  "slug": "848-24.jpg",
  "desc": "CueMix Pro on desktop display",
  "cls": "software",
  "prod": "848",
  "part": 3
 },
 {
  "idx": 97,
  "src": "MOTU 848 (25).jpg",
  "slug": "848-25.jpg",
  "desc": "MONITOR GROUP button row 1-12 macro",
  "cls": "macro",
  "prod": "848",
  "part": 3
 },
 {
  "idx": 98,
  "src": "MOTU 848 (26).jpg",
  "slug": "848-26.jpg",
  "desc": "CueMix PATCHBAY mic+line inputs to host",
  "cls": "software",
  "prod": "848",
  "part": 3
 }
];

export const byIdx = (i: number): Asset => {
  const a = ASSETS.find((x) => x.idx === i);
  if (!a) throw new Error(`no asset #${i}`);
  return a;
};

export const img = (i: number): string => `img/${byIdx(i).slug}`;

export const partAssets = (p: 1 | 2 | 3): Asset[] => ASSETS.filter((a) => a.part === p);
