// Image-coverage ledger (brief §0, §7, §8): every unique product image must
// appear at least once, and every image must sit inside an act whose product
// context is anchored by a text card. Generated from the actual shot list.
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { TIMELINE } from "../src/data/timeline.ts";
import { IMAGES } from "../src/data/images.ts";
import { ACTS, FPS, beatFrame } from "../src/data/grid.ts";

const PROJ = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const manifest = JSON.parse(fs.readFileSync(path.join(PROJ, "public", "images", "manifest.json"), "utf8"));
const aliases = Object.fromEntries(manifest.map((m) => [m.slug, m.aliases]));

const appearances = new Map();
for (const s of TIMELINE.shots) for (const slug of s.images) (appearances.get(slug) ?? appearances.set(slug, []).get(slug)).push(s);
const missing = IMAGES.filter((i) => !appearances.has(i.slug));
const unknown = [...appearances.keys()].filter((k) => !IMAGES.some((i) => i.slug === k));
if (unknown.length) throw new Error(`shots reference unknown images: ${unknown.join(", ")}`);

// text-anchor check: for every shot with images, the nearest preceding title/word/label card in the same act must be ≤ 6 beats back
let unanchored = [];
for (const s of TIMELINE.shots) {
  if (!s.images.length) continue;
  const prior = TIMELINE.shots.filter((t) => t.act === s.act && t.beat <= s.beat && t.text && ["title", "word", "label"].includes(t.text.role));
  const last = prior.at(-1);
  if (!last || s.beat - last.beat > 6) unanchored.push(`${s.act} rel ${s.rel} (${s.images.join(", ")})`);
}

const t = (f) => { const sec = f / FPS; return `${Math.floor(sec / 60)}:${(sec % 60).toFixed(2).padStart(5, "0")}`; };
const actName = Object.fromEntries(ACTS.map((a) => [a.id, a.name]));
const lines = [];
lines.push("# ASSET COVERAGE LEDGER — MOTU AVB Ecosystem 90-second montage reel", "", "Generated by `scripts/coverage.mjs` from the actual shot list (`src/data/timeline.ts`).", "");
lines.push("## Headline", "", "| | |", "|---|---|", `| Image files in repository root | **${manifest.reduce((a, m) => a + m.aliases.length, 0) + 3}** (incl. the 3 excluded filenames) |`, `| Byte-identical duplicate groups | **${manifest.filter((m) => m.aliases.length > 1).length}** |`, `| Unique product images requiring coverage | **${IMAGES.length}** |`, `| Covered | **${IMAGES.length - missing.length}** |`, `| Missing | **${missing.length}** |`, `| Images shown without a text anchor within 6 beats | **${unanchored.length}** |`, "");
lines.push("## Excluded (content verified, not filename-trusted)", "", "| File | Why |", "|---|---|", "| `MOTU 10pre (23).jpg` | Moog modular synthesizer — third-party hardware, not a MOTU product |", "| `MOTU 16A (3).jpg` | byte-identical to `MOTU 10pre (23).jpg` |", "| `MOTU 848 (6).jpg` | byte-identical to `MOTU 10pre (23).jpg` |", "");
lines.push("## Per act", "", "| Act | Images | Shots | Mean hold |", "|---|---|---|---|");
for (const a of ACTS) {
  const shots = TIMELINE.shots.filter((s) => s.act === a.id && s.images.length);
  const imgs = new Set(shots.flatMap((s) => s.images));
  const mean = shots.length ? shots.reduce((x, s) => x + (s.endFrame - s.startFrame), 0) / shots.length / FPS : 0;
  lines.push(`| ${a.name} | ${imgs.size} | ${shots.length} | ${mean ? mean.toFixed(2) + " s" : "—"} |`);
}
lines.push("", "## Full ledger", "", "| # | Image (all filenames it covers) | Product | Kind | Appears | Time | Act · shot |", "|---|---|---|---|---|---|---|");
IMAGES.forEach((img, i) => {
  const ap = appearances.get(img.slug) ?? [];
  const names = (aliases[img.slug] ?? [img.slug]).map((a) => `\`${a}\``).join("<br>");
  lines.push(`| ${i + 1} | ${names} | ${img.product} | ${img.kind} | ${ap.length ? ap.length + "×" : "**MISSING**"} | ${ap.map((s) => t(s.startFrame)).join(", ")} | ${ap.map((s) => `${actName[s.act]} · ${s.kind} @${s.rel}`).join("; ")} |`);
});
if (unanchored.length) lines.push("", "## Unanchored shots", "", ...unanchored.map((u) => `- ${u}`));
fs.writeFileSync(path.join(PROJ, "ASSET_COVERAGE_MONTAGE_REEL.md"), lines.join("\n") + "\n");
console.log(`unique images ${IMAGES.length}  covered ${IMAGES.length - missing.length}  missing ${missing.length}  unanchored ${unanchored.length}`);
if (missing.length) { console.log("missing:", missing.map((m) => m.slug).join(", ")); process.exit(1); }
if (unanchored.length) { console.log("unanchored:", unanchored.join("\n")); process.exit(1); }
