// CURATED asset registry — generated by scripts/build-manifest.mjs + copy-assets.mjs.
//
// Keyed by the stable index from the repository-wide visual inventory, NOT by
// filename. The supplied filename product prefixes are demonstrably unreliable:
// "MOTU 10pre (23).jpg", "MOTU 16A (3).jpg" and "MOTU 848 (6).jpg" decode to
// identical pixels. Identity here is a pixel hash; classification came from
// looking at every image on a contact sheet.
//
// UNLIKE the long-form video and the three-part reels, this master reel does
// not carry "every image must appear". It carries a CURATED set — 61 of the
// repository's 120 unique product images — chosen for the strength of the
// ecosystem story in 298 s. What is NOT relaxed is completeness per image:
// every image that IS selected is shown whole and uncropped at some point.
import { staticFile } from "remotion";
import manifest from "../asset-manifest.json";

export type Bucket = "10pre" | "16A" | "848" | "AVBSwitch" | "Network" | "Shared" | "Brand";

export type AssetEntry = {
  idx: number;
  file: string;
  aliases: string[];
  hash: string;
  w: number;
  h: number;
  fmt: string;
  ar: number;
  product: Bucket;
  tier: "hero" | "support";
  slug: string;
  ext: string;
  /** Auto-detected from the image's own four corners at asset-copy time. */
  bg: "light" | "mixed" | "dark";
  border: number;
};

export const ASSETS = manifest as AssetEntry[];
const BY_IDX = new Map<number, AssetEntry>(ASSETS.map((a) => [a.idx, a]));

export function meta(idx: number): AssetEntry {
  const a = BY_IDX.get(idx);
  if (!a) throw new Error(`No curated asset with index ${idx}`);
  return a;
}
export function img(idx: number): string {
  const a = meta(idx);
  return staticFile(`images/${a.slug}.${a.ext}`);
}
export const ar = (idx: number): number => meta(idx).ar;

export const LOGO = { motu: 121, shivansh: 122 } as const;

// ───────────────────────────────────────────────── Segment 1 — The Hook
export const HOOK = {
  studioA: 82, studioB: 14,
  cableFan16A: 63, cableFan848: 90,
  tease848: 107,
} as const;

// ─────────────────────── Segment 2 — The Thesis (One Engine, Three Front-Ends)
export const THESIS = {
  // The peer triptych — three front elevations, shown together, never as a ladder.
  elev10pre: 30, elev16A: 76, elev848: 85,
  // ECOSYSTEM MONTAGE (new technique, Section 3): three visibly different front
  // panels clubbed under one claim that is true of all three at once.
  face10pre: 9,   // ten mic/line/instrument combos
  face16A: 62,    // sixteen line outputs, no preamps at all
  face848: 18,    // talkback, A/B/C, mute, mono
  ess: 24, thunderbolt: 26, cuemixBadge: 43,
  discovery: 31,  // all three interfaces listed in one software window
  cuemixMonitor: 11,
  rtl: 105,
} as const;

// ───────────────────────────────────── Segment 3 — Capture (MOTU 10pre)
export const TENPRE = {
  hero: 39, rearElevation: 35, inserts: 5, meters: 15,
  lineOut: 16, headphones: 27, heroRight: 38, rearQuarter: 37,
} as const;

// ───────────────────────────────────── Segment 4 — Route (MOTU 16A)
export const S16A = {
  hero: 79, rearElevation: 51, lineOutBank: 62, opticalRow: 60,
  rearDetail: 74, patchbayBlue: 54, patchbayPurple: 55, meters: 58,
  modularSynth: 21, laptop: 56, ipad: 73, rearQuarter: 77,
} as const;

// ───────────────────────────────────── Segment 5 — Command (MOTU 848)
export const S848 = {
  hero: 110, control: 18, combos: 95, inserts: 93, headphones: 88,
  monitorGroup: 97, meters: 94, lineOut: 89, rearCluster: 91,
  rearQuarter: 108, patchbay: 98,
} as const;

// ─────────────────────── Segment 6 — The Network (MOTU AVB Switch)
export const NET = {
  builtInPort: 20,      // the interface's OWN Ethernet port — half the handshake
  switchPorts: 112,     // the Switch's RJ-45 cluster — the other half
  switchFront: 116,
  rj45Cable: 117,
  ieeeAvb: 115, milan: 100,
  topologyRender: 113, topologyDiagram: 68,
  clock: 118, qos: 119, gauge: 120,
} as const;

// ─────────────────────── Segment 7 — Synthesis & CTA (four-product climax)
export const CLIMAX = {
  tenpre: 41, s16a: 80, s848: 111, avbsw: 114,
} as const;

// ───────────────────────────────────────────────────────────────── audio
export const MUSIC = (slug: string): string => staticFile(`audio/music/${slug}.mp3`);
export const SFX = (name: string): string => staticFile(`audio/sfx/${name}.wav`);
export const VO = (): string => staticFile(`vo/voiceover-master-reel.mp3`);

export type SfxKey =
  | "encoder-detent" | "encoder-detent-hi" | "encoder-detent-lo" | "encoder-detent-top"
  | "encoder-turn"
  | "rj45-snap" | "rj45-snap-soft" | "talkback-engage"
  | "relay-tick" | "relay-tick-hi" | "relay-tick-lo"
  | "counter-tick" | "counter-tick-hi" | "rack-seat"
  | "avb-ping-hi" | "avb-ping-mid" | "avb-ping-lo" | "avb-ping-top" | "avb-ping-alt"
  | "gptp-sync" | "gptp-lock"
  | "data-stream" | "data-stream-short" | "data-stream-long" | "link-establish"
  | "panel-air" | "panel-air-soft" | "panel-air-hi";
